### ISSUE TITLE
force calculation

### ISSUE THREAD

**Issue by jxgxx** [xcompact3d/Incompact3d#10]
Hi all,

If I modify the cylinder case to another scenario, (cylinder moves from right to left with v=-0.1, while the incoming flow velocity v_in=0.9, the characteristic velocity still keep as 1 here, Re=40 for benckmark). Then the force in x-direction become discontinuous (see attached, I guarantee the CV always contain the cylinder inside).

But I expect the case should be equal to stationary cylinder case. Any reason causes that? Thanks.

**Comment by jxgxx** [comment]
Sorry, I failed to attach the x-direction coefficient behind the post.

**Comment by jxgxx** [comment]
Sorry, I failed to attach the x-direction coefficient behind the post.
"discontinuous" means can't converge. Most values fall to around 1.7, but a few values go to as high as 100, as low as -60

**Comment by fschuch** [comment]
I have a few considerations just to make sure that I understand your case.

You are moving the center of the cylinder (cex) from right to left. Are you calling genepsi3d or body (depending on ivirt value) to compute the new cylinder position every time step? Are you calling init_forces subroutine in order to repositionate the Control Volume where the coefficients are computed?

**Comment by jxgxx** [comment]
1) Yes. Move cex.
2) Calling body, use old school without lagrangian Polynomials.  
Code in geomcomplex :
"           r=sqrt((xm-cex+0.1*t)*(xm-cex+0.1*t)+(ym-cey)*(ym-cey))
           if (r .gt. ra) cycle
           epsi(i,j,k)=remp"
Code in body subroutine in navier.f90:
"  if (arg==0) then !First execution, initt epsi
     ep1(:,:,:)=zero
     call geomcomplex(ep1,xstart(1),xend(1),ny,xstart(2),xend(2),xstart(3),xend(3),dx,yp,dz,one)
  elseif (arg==1) then  !Any other iteration
    ep1(:,:,:)=zero
     call geomcomplex(ep1,xstart(1),xend(1),ny,xstart(2),xend(2),xstart(3),xend(3),dx,yp,dz,one)
     nvect1=xsize(1)*xsize(2)*xsize(3)
     do ijk=1,nvect1
        ux1(ijk,1,1)=(one-ep1(ijk,1,1))*ux1(ijk,1,1)+ep1(ijk,1,1)*(-1.0)
        uy1(ijk,1,1)=(one-ep1(ijk,1,1))*uy1(ijk,1,1)
        uz1(ijk,1,1)=(one-ep1(ijk,1,1))*uz1(ijk,1,1)
     enddo
  endif
"

3)Yes, and I increase the xld, xrd to guarantee the cylinder never go out of CV. I didn't change anything in force.f90 subroutine.

Appreciate for any comments. Thanks.

**Comment by jxgxx** [comment]
1)  Yes. Move cex.
2)  Calling body, use old school without lagrangian Polynomials.
Code in geomcomplex :
" r=sqrt((xm-cex+0.1t)*(xm-cex+0.1t)+(ym-cey)*(ym-cey))
if (r .gt. ra) cycle
epsi(i,j,k)=remp"
Code in body subroutine in navier.f90:
" if (arg==0) then !First execution, initt epsi
ep1(:,:,:)=zero
call geomcomplex(ep1,xstart(1),xend(1),ny,xstart(2),xend(2),xstart(3),xend(3),dx,yp,dz,one)
elseif (arg==1) then !Any other iteration
ep1(:,:,:)=zero
call geomcomplex(ep1,xstart(1),xend(1),ny,xstart(2),xend(2),xstart(3),xend(3),dx,yp,dz,one)
nvect1=xsize(1)*xsize(2)*xsize(3)
do ijk=1,nvect1
ux1(ijk,1,1)=(one-ep1(ijk,1,1))*ux1(ijk,1,1)+ep1(ijk,1,1)*(-0.1)
uy1(ijk,1,1)=(one-ep1(ijk,1,1))*uy1(ijk,1,1)
uz1(ijk,1,1)=(one-ep1(ijk,1,1))*uz1(ijk,1,1)
enddo
endif
"
3)Yes, and I increase the xld, xrd to guarantee the cylinder never go out of CV. I didn't change anything in force.f90 subroutine.

Appreciate for any comments. Thanks.

**Comment by fschuch** [comment]
The line:
        ux1(ijk,1,1)=(one-ep1(ijk,1,1))*ux1(ijk,1,1)+ep1(ijk,1,1)(-0.1)
does not seem correct and can potentially break the code, the better place to reduce the influx velocity is at inflow subroutine at BC-Cylinder.f90 file. You can change the line:
        bxx1(j,k)=one+bxo(j,k)*noise1
to:
        bxx1(j,k)=zpnine+bxo(j,k)*noise1

Anyway, I'm still making some tests and I will contact you soon.

**Comment by jxgxx** [comment]
I did that (bxx1(j,k)=zpnine+bxo(j,k)*noise1)  in inflow part, since the incoming flow should be 0.9.

The reason I made "+ep1(ijk,1,1)*(-0.1)" is to ensure the no-slip boundary condition along the cylinder curve. So that the streamline would be no penetration to the cylinder inside. I also add this in divergence subroutine:
"  if (ivirt.eq.0.and.ilag.eq.0) ep1(:,:,:)=zero
  do ijk=1,nvect1
    ta1(ijk,1,1)=(one-ep1(ijk,1,1))*ux1(ijk,1,1)+ep1(ijk,1,1)*(-0.1)
    tb1(ijk,1,1)=(one-ep1(ijk,1,1))*uy1(ijk,1,1)
    tc1(ijk,1,1)=(one-ep1(ijk,1,1))*uz1(ijk,1,1)
  enddo
"

**Comment by jxgxx** [comment]
I am not quite understand the purpose in init_force subroutine. What happened if skipping "call alloc_z()" (arg not equal to 0)?
Other parts should be good and clear.

**Comment by fschuch** [comment]
Drag and Lift coefficients are computed inside the control volume. In relation to the center of the cylinder, it extends xld to the left (-x-direction),  xrd to the right (x-direction), yld lower (-y-direction) and yud upper (y-direction). The init_force subroutine defines this volume, so in the attached the code it is computed every time step and as consequence, it follows the cylinder. The 'arg' equal to 0 is to prevent the code to allocate variables that were already allocated in the first call at incompact3d.f90.

**Comment by jxgxx** [comment]
Keep CV and the cylinder center relatively static. I will test it, and update here if it works. Thanks for your time, Felipe.

**Comment by jxgxx** [comment]
Hi Felipe,
From my testing results, the oscillation in x-force became better, but still existed. Around 5-10 iterations in every 500 iterations, the coefficients can reach to as high as 10. I was wondering what the test results look like in your side?

Thanks,
Xixiong

**Comment by jxgxx** [comment]
Just follow up to see if you have any updates regarding the moving case test. Thanks.

**Comment by fschuch** [comment]
I attached lift and drag coefficient; the black dotted line represents the averaged value from time 10 to 30.

![drag](https://user-images.githubusercontent.com/37457501/39540280-90d2ba64-4e18-11e8-9b20-7a49ae989354.png)
![lift](https://user-images.githubusercontent.com/37457501/39540281-90f5178a-4e18-11e8-9681-0697121464c4.png)

Can you correlate the time between oscillations with dx size and the velocity of the cylinder? I mean, it is probably happening at the same relative position between the cylinder (and/or CV) and the mesh.

**Comment by fschuch** [comment]
Yes, that is the point. The peaks are due to the cylinder moving inside the Cartesian mesh. However, I am not sure about how to solve it.

**Comment by jxgxx** [comment]
If it is due to the irregular geometry of cylinder (using Cartesian nodes only, it is impossible to describe the exactly geometry of a cylinder) , maybe I can try a prism instead.

Is it possible that you discuss with other authors or users about this issue?  Solving this problem is very important to me. Very appreciate if you can spend some time on it.

Xixiong

**Comment by xcompact3duser** [comment]
Dear all,

The computation of forces for a moving object is not (yet) possible with Incompact3d. At the moment nothing is done do deal with mesh nodes that are inside/outside the object at one time step and then outside/inside the object. This is a very tricky problem which I am hoping to solve in the next few months (there is a PhD at Imperial College working on moving IBM).

All the best,

Sylvain

**Comment by jxgxx** [comment]
Hi Dr. Laizet,

Just come to follow up if you could spare your time to answer above question. I found the streamline, as well as the flow field solution overall ok when adding the moving motion.

Thanks in advance.

Best,
Xixiong
