### ISSUE TITLE
Force Calculation on Moving objects

### ISSUE THREAD

**Issue by dineshkumarreddyg36** [xcompact3d/Incompact3d#112]
I wish to know that whether the **forces.f90** module works for both **moving objects** and the **stationary objects** or only for the later one.  Could someone please comment on it? 
When I tried to calculate the forces acting on a transversely oscillating Cylinder (Forced Oscillation) I've observed the Spurious oscillations in the Coefficient of lift and Coefficient of Drag as shown below
![C_l](https://user-images.githubusercontent.com/106377425/183873238-37a69a2b-c993-46ce-a90c-12aa42f45a2d.PNG)

**Comment by mathrack** [comment]
Please do not post several times similar questions. You will get some answer [at this location](https://github.com/xcompact3d/Incompact3d/discussions/111) whenever someone has an answer.
