### ISSUE TITLE
TGV case does not run in DEBG mode

### ISSUE THREAD

**Issue by slaizet** [xcompact3d/Incompact3d#128]
**Describe the bug**
TGV case does not run in DEBUG mode

**To Reproduce**
1. Git version: current master branch v4.0-114-ge56485b
2. Compilation: options -DDEBG with gfortran compiler 11.2
3. Set-up: TGV
 DIV U* max mean=   5.3237008523459193E-003   1.0803248978164840E-003
 ## Solve Poisson before1 pp3  -1.6591250762536540E-008
 ## Poisson11X Start rw2   -1.3312986680372684E-007
 ## Poisson11X Start rw1   -6.2943711029358916E-006
  
 ***** Using the generic FFT engine *****
  
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node turbulence exited on signal 11 (Segmentation fault).

**Comment by mathrack** [comment]
The TGV case is running with `make BUILD=debug` (without the `-DDEBG` flag).

Test performed with gcc 11.2.0 and OpenMPI 4.1.0.

**Comment by slaizet** [comment]
ok, silly question: what is the difference between the two options?

**Comment by mathrack** [comment]
The DEBG flag is used approximately everywhere to compute / print plenty of things. I recommend to avoid using it as much as possible. The output of the code is very difficult to read when this flag is present.

**Comment by mathrack** [comment]
As a side remark, it would be interesting to quantify the number of lines we could save if the DEBG flag was removed.
