### ISSUE TITLE
Is streching working in cylinder code properly?

### ISSUE THREAD

**Issue by Rajosik** [xcompact3d/Incompact3d#13]
Cylinder code (latest updated) is running with stretching without -DSTRETCHING option in makefile under the cylinder tag.  Mesh is generated properly with yp.dat file with stretching and code is running. But the code crashes after few iterations if -DSTRETCHING option is opted under the cylinder. Is the solver is solving the problem considering the stretching properly if -DSTRETCHING  option is not opted?

**Comment by fschuch** [comment]
I'm running some tests. I just want to check what value you are using for beta on prm.

Enviado do meu iPhone

Em 8 de mai de 2018, à(s) 09:24, Rajosik <notifications@github.com<mailto:notifications@github.com>> escreveu:


Cylinder code (latest updated) is running with stretching without -DSTRETCHING option in makefile under the cylinder tag. Mesh is generated properly with yp.dat file with stretching and code is running. But the code crashes after few iterations if -DSTRETCHING option is opted under the cylinder. Is the solver is solving the problem considering the stretching properly if -DSTRETCHING option is not opted?

**Comment by Rajosik** [comment]
I have used beta=1.2.

**Comment by fschuch** [comment]
The code can not compute forces coefficients properly with stretching,  it is in our known issues list, so I recommend removing the flag -DFORCES. I figured out that the code was not compiling without the flag, but I fixed it in the last commit.
You are right about the -DSTRETCHING flag, the cylinder case can run with stretching without it at this moment. However, the code is in a pre-release version, the compile option may be necessary for the future.
The code ran properly in my test, please, let me know if you have any question.

**Comment by Rajosik** [comment]
The stretching option in cylinder code seems stretching is implemented while meshing is concerned but the code is not simulating considering as stretching. The results in channel code are not matching well with the cylinder code with the same condition.

**Comment by ricardofrantz** [comment]
I’m sorry but I cannot understand your question.  Could you please try to rephrase it?

**Comment by Rajosik** [comment]
Using the cylinder type flow condition, the stretching can be implemented without using -DSTRETCHING flag. The mesh is seen in the post-processing, but the result of a simulation over flat plate doesn't match with the Blasius boundary layer in the laminar region. Whereas, same mesh size with stretching giving a good match in channel flow type. From this, it seems that the code is not solving equation considering it as stretched mesh and working like normal uniform distributed mesh which leads to a poor result for flow over a flat plate.

**Comment by ricardofrantz** [comment]
If you try to use istret.ne.0 and compile the code without the flag. It could generate a stretched mesh, but I’m sure it will compute the derivares for the homogenous one. So it is completely wrong.

We should add the #ifdefs to better avoid the istret flags. Thank you for noticing.
