### ISSUE TITLE
Unusual issues restarting cases with large meshes on Archer2

### ISSUE THREAD

**Issue by mattfalcone1997** [xcompact3d/Incompact3d#135]
It appears that the restart does not work properly for large meshes using the MPI-IO build on ARCHER2. I have been using a fork of Incompact3D  developed for implementing the recycling-rescaling method for spatially accelerating turbulent boundary layer method. However, I have reproduced it using the already implemented turbulent boundary layer case on Incompact3D. The issue occurs on large meshes (the one tested is at around 600M elements) and only after a restart where it appears that the data read in from the checkpoint file is incorrect notably for the velocity field although it seems the pressure is fine. I have reproduced the problem using a version of master branch modified to output the data immediately after the `call restart`. This was tested on ARCHER2 due to the large size of the mesh so this could be a problem with my environment but I have tested using different compilers with both O2 and O3 optimisation flags. The instructions to reproduce the problems are below although the issues should be apparent at least on commit (SHA: 723961c2c6f8ff3530bfb6d4a0c5bd8c9bb32ee4 (02/08/2022)) with the maximum velocities appearing very different to the previously run simulation. 

# Tests
A modified version of commit 723961c2c6f8ff3530bfb6d4a0c5bd8c9bb32ee4 has been tested such that the restarted simulations are immediately outputted after the `call restart` command. The program is then exited. The modified code can be found on branch master_testing of the Incompact3D [fork](https://github.com/mattfalcone1997/Incompact3d). This should mean that the results show what has been restarted from file. 

## Summary of what has been tested
1. A smaller mesh which runs correctly. Files attached below:
   * [input_restart1.i3d](https://github.com/xcompact3d/Incompact3d/files/10126413/input_restart1.txt): Original file which produces data for restart
   * [input_data1.i3d](https://github.com/xcompact3d/Incompact3d/files/10126414/input_data1.txt):  File for the restart
   * [run_x3d.sh](https://github.com/xcompact3d/Incompact3d/files/10126449/run_x3d.txt): slurm submission script
3. A larger mesh which doesn't run correctly
   * [input_data2.i3d](https://github.com/xcompact3d/Incompact3d/files/10126416/input_data2.txt): Original file which produces data for restart
   * [input_restart2.i3d](https://github.com/xcompact3d/Incompact3d/files/10126415/input_restart2.txt): File for the restart
4. Case 2 using ADIOS2 which runs fine
   * uses same input files as case 2
   * adios used for the output rather than MPI-IO directly
   * adios2_config.xml same as channel flow example
 
# To reproduce the error on archer2.
## Getting the testing code.
 I have attached the output of the `git diff` command to indicate how this has been changed from master which is the same as commit SHA 723961c2c6f8ff3530bfb6d4a0c5bd8c9bb32ee4 ([git_diff.log](https://github.com/xcompact3d/Incompact3d/files/10126417/git_diff.log))
1. `mkdir Incompact3D && cd Incompact3D`
2. `git init`
3. `git remote add origin https://github.com/mattfalcone1997/Incompact3d.git`
5. `git pull origin master_testing`

## Configuration and compilation options
6. `mkdir build && cd build`
7. Without Adios2:
  `cmake -S .. -B .`
6.With ADIOS2
   `cmake -S .. -B . -DUSE_ADIOS2=ON -DADIOS2_ROOT="adios2_build_path"`
8. `make`

## Errors
Output files are attached. clear differences were observed in u, v , w maximum values after the restart and the output data seems to be wrong (images are attached).

## Expected behaviour
I expect the simulation to restart and continue as it was before the restart

## Notes
I have also tried with different compilers and I reduced the level of optimisation to O2 to no effect. I have not exhaustively tested the issue and the problem may well be related to my setup at compile or run time.

I have attempted to give as much information as I could but let me know if you have any questions
Thanks in advance,
Matthew Falcone
## Large mesh
* Before restart
   * velocity u
   <img src="https://user-images.githubusercontent.com/56128322/204889596-0ed17c34-8e87-480f-9688-32fc7347bee4.png"  width="400">

   * velocity v
   <img src="https://user-images.githubusercontent.com/56128322/204889588-b228c444-98cb-40be-80d6-4dabeb80302e.png"  width="400">

   * pressure
<img src="https://user-images.githubusercontent.com/56128322/204889594-2bc18abb-32d0-4686-be1f-6bf92970da08.png"  width="400">

* After restart
   * velocity u
   <img src="https://user-images.githubusercontent.com/56128322/204890210-819dcf34-ca98-4d4e-8afe-e4bb89207f58.png"  width="400">

   * velocity v
   <img src="https://user-images.githubusercontent.com/56128322/204890207-a2a5ae0d-61aa-4615-a053-7b053def84ff.png"  width="400">

   * pressure
<img src="https://user-images.githubusercontent.com/56128322/204890208-9e207360-4e5c-49ba-bdb4-c3adc91cae15.png"  width="400">

## Small mesh
* Before restart
<img src="https://user-images.githubusercontent.com/56128322/204890789-cc2cb036-d124-48ef-b706-5e4fcec01462.png" width="400">

* After restart
<img src="https://user-images.githubusercontent.com/56128322/204890787-6a79025b-a88f-426a-be92-73cc5b2b5f11.png"  width="400">

## Large mesh with Adios2
* Before restart
<img src="https://user-images.githubusercontent.com/56128322/204889189-98e409a3-f04a-40ee-9c34-3b63cd4805b4.png"  width="400">

* After restart
<img src="https://user-images.githubusercontent.com/56128322/204889139-21f1d749-cb2f-4997-87ea-3966257d856d.png"  width="400">

**Comment by pbartholomew08** [comment]
Hi, thanks for all the information supplied so far. To help narrow down possible causes of the bug - are you setting either of these variables in the Makefile when building?
```
#   -DDOUBLE_PREC - use double-precision
#   -DSAVE_SINGLE - Save 3D data in single-precision
```

**Comment by pbartholomew08** [comment]
Apologies for deleted post I see you are using CMake, not the Makefile, my mistake!

**Comment by mathrack** [comment]
Hello,
Please confirm the MPI library used and the version.
Thanks

**Comment by mattfalcone1997** [comment]
I used the `module load PrgEnv-gnu` to load the library. I have also tested with `PrgEnv-cray` library

**Comment by mattfalcone1997** [comment]
> Hello,
> 
> Please confirm the MPI library used and the version.
> 
> Thanks

The results are from compiling with the `PrgEnv-gnu` module with the default version and I have also tested with gcc/9.3. I also appear to get similar issues with `PrgEnv-cray` module but I have tested less extensively with that one. I believe both load the cray-mpich/8.1.4 library by default.

**Comment by pbartholomew08** [comment]
Yeah, from the docs
```
Cray MPICH 8.1.4 is based upon ANL MPICH 3.4a2
```

**Comment by pbartholomew08** [comment]
The branch in the above pull request (WIP) adds some additional checks within the I/O module, if you have a chance to try it could you report any errors that it flags up? It will check the write and read steps.

**Comment by mathrack** [comment]
To investigate the potential issue associated with integer overflow, for the run writing the restart file and for the run reading it, could you give :

- number of CPUs
- p_row and p_col for the 2D domain decomposition

Cheers

EDIT : The number of CPUs actually does not change the integer overflow issue. Please let me know if the problem is fixed after commit https://github.com/xcompact3d/Incompact3d/pull/136/commits/a8a01983d154e7e0feac50a2847f5cf32d39b086

**Comment by mattfalcone1997** [comment]
> To investigate the potential issue associated with integer overflow, for the run writing the restart file and for the run reading it, could you give :
> 
> * number of CPUs
> * p_row and p_col for the 2D domain decomposition
> 
> Cheers
> 
> EDIT : The number of CPUs actually does not change the integer overflow issue. Please let me know if the problem is fixed after commit [a8a0198](https://github.com/xcompact3d/Incompact3d/commit/a8a01983d154e7e0feac50a2847f5cf32d39b086)

I was using 32 nodes with 128 cores per node. I have also tested with 128 nodes with 128 cores per node (). I use 0, 0 with p_row and p_col so that decomp_2d works it out although the output indicates that with 32 nodes it used 64 x 64 decomposition and with 128 nodes it uses 128x128. I will check the commit.

**Comment by mattfalcone1997** [comment]
I believe the problem has now been resolved. I have checked both the output files and run the restart for a further 100 iterations. I'll let you know if I have any more issues but I think we can close this now.

**Comment by pbartholomew08** [comment]
Reopening as would like to figure out why it wasn't working

**Comment by pbartholomew08** [comment]
Thanks for all the information provided so far and bringing this to our attention @mattfalcone1997

**Comment by mathrack** [comment]
@mattfalcone1997 thank you for your feedback, we will try to nail it more accurately and will merge a proper fix on master

**Comment by mattfalcone1997** [comment]
This may be wrong as I am not sure of the details of how fortran handles the integer arithmetic, but is it possible that the multiplication on line 330 cast to integer(4) due to the types of `subsizes` etc. resulting in overflow before assigning to integer(8) of `disp`? This could possibly explain why it only occurs on larger meshes. Also, this may be the reason it doesn't seem to occur for the `write_snapshot` which does not write several arrays to one file.

**Comment by pbartholomew08** [comment]
I think so, just want to narrow down that that is the reason and then we can merge the above fixes into main. The rest are general safety checks.

**Comment by mattfalcone1997** [comment]
I could run a test with a scalar. I think the pressure may have been fine as it was the last variable to write to/ read from the checkpoint file. Looking at the restart subroutine, phi is written afterwards so it should break the pressure.  Also, the checkpoint file sizes are very different 53G vs 17G

**Comment by mattfalcone1997** [comment]
I have attached the slurm output file with the `varname`, `disp`, `sizes(1)*sizes(2)*sizes(3)*disp_bytes`, `int(sizes(1),kind=MPI_OFFSET_KIND)* int(sizes(2),kind=MPI_OFFSET_KIND)*int(sizes(3),kind=MPI_OFFSET_KIND)*int(disp_bytes,kind=MPI_OFFSET_KIND)` output for the uncorrected case in the write subroutine. It shows that term 3 is much smaller than term 4 and that term 4 is larger than the maximum value for a signed 4-byte integer. 
[slurm-2694854.log](https://github.com/xcompact3d/Incompact3d/files/10132547/slurm-2694854.log)
