### ISSUE TITLE
Asymmetric results for channel flow 

### ISSUE THREAD

**Issue by hietwll** [xcompact3d/Incompact3d#14]
Hello, all
I just tested the channel flow case without any modification to the latest version of the codes. But the results seem to be incorrect, because the flow is not symetrical to the center plane.

Figure below shows the Q isosurface (Q =0.01) at itime=80000. It looks like that there are more vortex stuctures near the upper wall.
![q-vor-32](https://user-images.githubusercontent.com/14847853/40033390-cd0bde7c-582a-11e8-9a87-a0ecad2cb8d7.png)

The statistics also prove this point. Though mean velocity is symetrical to the center plane, the rms velocities or turbulent kinetic energy show evident asymmetry. Turbulence fluctuations are stronger in upper-wall than those in lower-wall.
![y-urms](https://user-images.githubusercontent.com/14847853/40033542-677bea74-582b-11e8-8c10-c84e972fc14e.png)

I have tried to run the simulations for a longer time and write my own statistic functions, the results are still the same.  Has anyone met this problem?

**Comment by hietwll** [comment]
Hello all,
I found the reason is just that the simulations did not run long enough. It takes about 300000 iterations for the turbulence to be fully developed with the current parameter configurations. Maybe the time step could be set a little larger to reduce the total iteration times.

It is also interesting that the upper wall always reaches turbulent state first. Why dose this happening?
![ani](https://user-images.githubusercontent.com/14847853/40153442-7291b744-59bc-11e8-8e85-87330b66cc67.gif)

**Comment by fschuch** [comment]
Maybe the rotation applied to the channel for a few time steps is causing the asymmetry, please take a look at [convidiff.f90](https://github.com/xcompact3d/Incompact3d/blob/f9e2a2eb89d2eef83c94282e2c593447624e9bf5/convdiff.f90#L284). It is used to accelerate transition to turbulence.

**Comment by xcompact3duser** [comment]
It is definitely asymmetric because of the initial rotation used to trigger turbulence.
