### ISSUE TITLE
Issues with istret=3

### ISSUE THREAD

**Issue by mattfalcone1997** [xcompact3d/Incompact3d#140]
I am implementing a temporally developing turbulent boundary layer following the method of [Kozul et al. 2016](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/direct-numerical-simulation-of-the-incompressible-temporally-developing-turbulent-boundary-layer/4F73179844DB762A5D4B9F8510FCADEB). The basis of this approach uses a fixed wall at the top of the computation domain modelled as a no-slip wall and a uniform moving wall at the bottom and periodic BCs in the other directions. The Poisson equation uses Neuman BC in the wall-normal directions (same as doubly periodic channel flow). This method works fine if `istret=2` or `istret=0` is used but fails after less than 10 timesteps if `istret=3` is used. I have reproduced this on the normal channel flow case with modified versions of the channel flow example on the latest commit. I am unsure if this is a limitation of istret=3, an issue with my case setup or a bug. The branch for the temporal boundary layer is found [here](https://github.com/mattfalcone1997/Incompact3d/tree/tbl_temp). It is also noticeable that the divergence of velocity is substantially degraded when using `istret=3` for example in turbulent boundary layer cases div U max and mean are ~10^{-7} whereas when using istret=0 or istret=2 it ~10^{-14}.

### Build steps
1. `git clone -b master https://github.com/xcompact3d/Incompact3d.git .`
2. `sed -i '30 i \\t\t    BC-Cavity.f90' src/CMakeLists.txt` (This file is missing from the CMakeLists.txt file)
3. `mkdir build && cd build`
4. `module load cmake`
5. `module load PrgEnv-gnu`
6. `cmake -S .. -B .`
7. `make`

### Test cases based on Channel example
1. Coarse mesh with istret=0 (checks it is the coarse mesh at the boundary) - works 
  * [input1.txt](https://github.com/xcompact3d/Incompact3d/files/10673984/input1.txt)
  * [output1.txt](https://github.com/xcompact3d/Incompact3d/files/10673983/output1.txt)
2. Fine mesh with istret=2 (check stretching to both sides) - works
  * [input2.txt](https://github.com/xcompact3d/Incompact3d/files/10673982/input2.txt)
  * [output2.txt](https://github.com/xcompact3d/Incompact3d/files/10673981/output2.txt) 
3. Fine mesh with istret=3 - fails
  * [input3.txt](https://github.com/xcompact3d/Incompact3d/files/10673978/input3.txt)
  * [output3.txt](https://github.com/xcompact3d/Incompact3d/files/10673980/output3.txt)

Let m know if you need more information.

**Comment by slaizet** [comment]
OK, can you try with an explicit time advancement? I suspect that this is the problem.

**Comment by mattfalcone1997** [comment]
I have switched off the implicit part (set iimplicit=0). It diverged at more or less the same bit. I have attached the input and redirected output
[output4.txt](https://github.com/xcompact3d/Incompact3d/files/10676338/output4.txt)
[input4.txt](https://github.com/xcompact3d/Incompact3d/files/10676339/input4.txt)

**Comment by slaizet** [comment]
OK thanks, we will look into this.

**Comment by slaizet** [comment]
I had a first look into this. I tried with istret=3 and a large beta, it is working fine (the mesh is more or less uniform but it is going via the stretching subroutine). I cannot see anything suspicious. It will require a more in depth investigation!
Sylvain

**Comment by mattfalcone1997** [comment]
Yes, I had also found this at beta=100 on my temporal boundary layer case.

**Comment by slaizet** [comment]
Okay, I think I have found the issue. Please can you uncomment line 837 in poisson.f90 ?
[call matrice_refinement() to be uncommented]
It seems to be working fine here. Please let me know!
Cheers,
Sylvain

**Comment by mattfalcone1997** [comment]
Yes, it seems to be working fine here as well. My temporal boundary layer appears to be working as well. I have attached the input and output files for reference.
[input5.txt](https://github.com/xcompact3d/Incompact3d/files/10699900/input5.txt)
[output5.txt](https://github.com/xcompact3d/Incompact3d/files/10699901/output5.txt)

Thanks for your help!
