### ISSUE TITLE
statistics read problem at restart

### ISSUE THREAD

**Issue by fangjian19** [xcompact3d/Incompact3d#147]
**Describe the bug**

A possible bug in reading statistics when restart. 
The mean flow statistics files were overwritten before reading previous mean flow field. 

the program calls xcompact3d -> postprocessing -> overall_statistic

In the beginning of subroutine overall_statistic, it reads:

   if (itime.lt.initstat) then
       return
    elseif (itime.eq.initstat) then
       call init_statistic()
    elseif (itime.eq.ifirst) then
       call restart_statistic()
    endif

For a restart case, itime>initstat and itime=ifirst-1, which will lead to the statistics being calculated and overwritten before reading a previous field.

This will lead to the statistics not correctly calculated.

**To Reproduce**
1. Git version
2. Compilation options
3. Set-up

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pbartholomew08** [comment]
Hi @fangjian19 this looks like a logic bug in the code - could you try replacing
```
elseif (itime.eq.ifirst) then
  call restart_statistic()
end if
```
with
```
elseif (itime .eq. (ifirst - 1)) then
  call restart_statistic()
end if
```
as you have described in the problem statement, I believe this should fix the issue?

**Comment by mathrack** [comment]
Hello,

`postprocessing` is called at the end of the time step. I think it is not possible to have `itime = ifirst-1` at the end of the time step.

**Comment by pbartholomew08** [comment]
Actually yes ^ - in that case how do you have `itime = ifirst - 1` or what makes you think that is so?

**Comment by fangjian19** [comment]
Hi Guys,

Many thanks for your prompt replies.

It happened when I tried to resume a previous simulation.

For example,
  The previous job stopped at itime=2800 (the statistics starts from earlier time, initstat=2000), and the new job starts from 2801, i.e., ifirst=2801.

the program goes:

program xcompact3d
  call init_xcompact3d()  ! itime=2800, read from restart0002800.info
  call postprocessing(rho1,ux1,uy1,uz1,pp3,phi1,ep1) 
  .....
  ......
  call overall_statistic(ux1, uy1, uz1, T, pp3, ep1) 
  ......
  ! here itime = 2800, but ifirst=2801. So the program will calculate statistics without read a previous field or iniialise the mean variables.
  if (itime.lt.initstat) then
       return
    elseif (itime.eq.initstat) then
       call init_statistic()
    elseif (itime.eq.ifirst) then
       call restart_statistic()
    endif

see the attached screenshot of the log file.

![image](https://user-images.githubusercontent.com/6450466/220403274-89b726db-faf2-4a2f-8729-dac0f64f47f2.png)

The program first overwrote the statistic field and then read the same file that has been overwritten. 
I suggest the following modification to the subroutine overall_statistic
    elseif (itime.eq.ifirst-1) then
       call restart_statistic()
       return
    endif

**Comment by fangjian19** [comment]
Another suggestion, users may not need to collect statistics for every step. We may add a variable to the program to let the statistics be calculated, for example, every 50 steps. This will save some computing resource.

**Comment by mathrack** [comment]
Hello,

Looking at the current code, I do not understand how the subroutine statistics/overall_statistic or case/postprocessing could be called before the end of the first time step. Please share the prm file used, and the source code if you are not using the current version.

**Comment by fangjian19** [comment]
> 

I see the problem. The version I am used is different with the one on the master branch..
![image](https://user-images.githubusercontent.com/6450466/220602501-01305498-4cdb-4b37-bd47-58a07c6494da.png)
The line of 
call postprocessing(rho1,ux1,uy1,uz1,pp3,phi1,ep1)
immediately after 
call init_xcompact3d()
cause the problem


I have attached the src files I am using. 
[src.zip](https://github.com/xcompact3d/Incompact3d/files/10802949/src.zip)

**Comment by mathrack** [comment]
The bug you are observing seems to be tightly connected with the modifications you did. I will close the present issue because it does not concern the code available on github.
