### ISSUE TITLE
Compute statistics at a user-defined sampling rate

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/Incompact3d#148]
A suggestion, users may not need to collect statistics for every step. We may add a variable to the program to let the statistics be calculated, for example, every 50 steps. This will save some computing resource.

_Originally posted by @fangjian19 in https://github.com/xcompact3d/Incompact3d/issues/147#issuecomment-1438788771_

**Comment by mattfalcone1997** [comment]
I am happy to do this as I have already done it on my own version. How can I add these changes, I am new to this stuff.

**Comment by pbartholomew08** [comment]
Hi Matt, excellent. Under "development" (to the right of this screen) you should be able to click "Create a branch" to open a pull request from your fork (if you haven't created one already you can click the "fork" button at the top of the screen). This should open a pull request linked to this issue showing your commits relative to the main branch. Once ready we can then merge this in.

And thanks for the interest in helping out!

**Comment by mattfalcone1997** [comment]
Under development, it just says, "No branches of pull requests". There does not appear to be any other options.

**Comment by pbartholomew08** [comment]
Hmm, ok in that case I think if you simply create a branch on your fork and open a pull request against this repository then we can link it back to the issue. Happy to walk through if this is not familiar to you

**Comment by mattfalcone1997** [comment]
I am running a channel flow case, I'll check against the benchmark data when its done.

**Comment by mattfalcone1997** [comment]
I have tested the statistics. It seems to work. I have uploaded images of statistics on a comment on the pull request.
