### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jhasbestan** [xcompact3d/Incompact3d#149]
Hi All
can you elaborate on how to visualize the output (field data)?  I see a data folder with velocity components and vorticity such as vort-309.bin  Do we have to convert them to a format recognizable by paraview? 
Thanks

**Comment by pbartholomew08** [comment]
Navigating to the `data/` directory in the Paraview "open" dialogue should show `snapshot-xxx.xdmf` files as a series. Opening this series will then read the various `vort-xxx.bin` (and likewise velocity, pressure, etc.) files for visualisation.

**Comment by pbartholomew08** [comment]
As this is not really an issue I am going to close the issue, please use the `Discussions` tab for questions if you have further problems.

**Comment by jhasbestan** [comment]
Perfect, thanks!
