### ISSUE TITLE
are LES models working?

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [xcompact3d/Incompact3d#15]
Hi everyone,

Greetings. So I am trying to use Explicit Dynamic Smagorinsky LES model, but I am not sure whether it is working ( are the all the LES models has been checked or validated?) or not? Or am I making any mistakes during compilation? The changes I am making are following:

FLOW_TYPE = Channel-flow# TGV# Channel-flow# Cylinder
OPTIONS = -DVISU -DVISUEXTRA -DDOUBLE_PREC -DPOST -DELES -DSAVE_SINGLE -DVERSION=\"$(GIT_VERSION)\" #all above   #Channel-flow

These are the changes I am making in the Makefile.

4      #jLES       #LES Model (0:DNS, 1:iLES, 2:Explicit Simple Smagorinsky, 3:Explicit Wall-Adaptive LES, 4: Explicit Dynamic Smagorinsky LES)

This the only change I made in the BC-Channel-flow.prm.

I am attaching a screenshot of the output from the terminal.
![jles4](https://user-images.githubusercontent.com/39419978/40287418-7217d8d8-5c6a-11e8-9811-8bc39c07e5ed.png)

At line number 4 in the picture, (output from subroutine smag)
smag nut1     min max=    0.0000000000000000        0.0000000000000000
At line number 16 in the picture, (output from subroutine dynsmag)
dsmag nut1     min max=    0.0000000000000000        0.0000000000000000  
The passed value of nut1 to the subroutine lesdiff is
nut1   0.0000000000000000        0.0000000000000000 

All these values are zero, are they should be zero? I printed out the value of FSGS (where the value of FSGS is coming from) which is zero, which makes all the values of nut1 zero, probably.

In the subroutine dynsmag, !FILTERING THE NON-CONSTANT CONSTANT, I don't understand this part.

I am seeking attention from the authors or who is using the LES models.

Best Regards,
Rubel Chandra Das.

**Comment by hietwll** [comment]
Hi Rubel,

The eddy viscosity ``nut1`` should not be zero. The model parameters ``maxdsmagcst`` and ``FSGS`` need to be specified when using dynamic Smagorinsky model. 

I am not familiar with this model. It seems that ``maxdsmagcst`` could be set to ``0.18*0.18=0.0324`` and ``FSGS`` could be set to ``1.0``.

**Comment by RUBEL-CHANDRA-DAS** [comment]
Thank you, Mr. Ricardo Frantz and Mr. Zhuo Wang. I do have another question which is described below.

I am confused about the calculation of Lij, the paper (Lilly 1992) mentioned that Lij (Page 633, Equation Number 7) is between "del" and "2*del".  From the paper, L_ij = T_ij - bar(t_ij), where T_ij is the residual (SGS) stress tensor at the test-filter scale (2del), t_ij is the residual stress tensor at the filter scale (del). So my question is that at what exact grid size, the parameters have been calculated in the Incompact3d Code (les_models.f90). Another question is that filtering at gird size "2*del" is equal to the filtered quantities at gird size "del" multiplied by 2, is that correct?

Best Regards,
Rubel Chandra Das.
[lilly1992.pdf](https://github.com/xcompact3d/Incompact3d/files/2021369/lilly1992.pdf)

**Comment by ricardofrantz** [comment]
The _del_ you are mentioning is the mesh filter. You can choose the metric, but the code is programmed with the classic option - have a look at les_models.f90 line [16](https://github.com/xcompact3d/Incompact3d/blob/f9e2a2eb89d2eef83c94282e2c593447624e9bf5/les_models.f90#L16)

The test filter, in this case, imposed by a filtering operation based on the compact operator (see Lele (1992 set of coefficients C.2.8 page 40) is configured to represent _2del_. Have a look at the [subroutine coefficients](https://github.com/xcompact3d/Incompact3d/blob/f9e2a2eb89d2eef83c94282e2c593447624e9bf5/filter.f90#L1529) in filter.f90

Keep in mind that the filter.f90 is not very well programmed, therefore when filtering in periodic conditions, you can't use the p's in the call. See for example [here](https://github.com/xcompact3d/Incompact3d/blob/f9e2a2eb89d2eef83c94282e2c593447624e9bf5/les_models.f90#L647).

Don't forget the double precision!
