### ISSUE TITLE
Lagrangian interpolation of any variable (i.e. Lij, Mij) in les_models.f90

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [xcompact3d/Incompact3d#16]
Hi everyone,

Greetings. If I want to do Lagrangian interpolation (or maybe trilinear interpolation) of any variable (i.e. Lij, Mij) in the les_models.f90, do I have to do it like Lagrangian interpolation (i.e. lagpol*(u)) in IBM implementation. Though the interpolation procedure will be quite different in my case, I think. Because in IBM, you are just interpolating directly the velocity component. In my case, I am having difficulty with the defining the size of the array of the variables due to domain decomposition. Besides, I need to use the local coordinates of the variables being interpolated. I'll really appreciate if anyone can help/suggest/guide me how I can do the interpolation.

Best Regards,
Rubel Chandra Das.

**Comment by RUBEL-CHANDRA-DAS** [comment]
Dear Mr. Felipe Nornberg Schuch,

Thank you for your response. I want to implement the Lagrangian-averaged scale-invariant SGS model (C. Meneveau, T. Lund, and W. Cabot, “A Lagrangian dynamic subgrid-scale model of turbulence,” J. Fluid Mech. 319, 353 (1996).). 

For this purpose, I need to interpolate LMij and MMij at location (x-u*dt) which is not fixed (page 364, Eq. 3.12). In doing so, I am having difficulty to do the Lagrangian interpolation of the variables of LMij and MMij at local coordinates located at different pencil at the different time. 

I was trying to relate the Lagrangian interpolation used in IBM to my case, but the variables related to LMij and MMij in the les_models.f90 are different than the interpolated "u" in IBM. Besides I am having a hard time to understand the IBM implementation especially subroutine lagpol*(u). For instance, I don't know the purpose of the following variables:
#npif# The highest number of fluid-points at each boundary (0, 1, 2 or 3)
#izap# First fluid-point jump ? (0: no, 1: yes=advised).

If anyone can give me some directions on the above-mentioned problem, I'll be really grateful.

Best Regards,
Rubel Chandra Das.
[meneveau1996.pdf](https://github.com/xcompact3d/Incompact3d/files/2023911/meneveau1996.pdf)

**Comment by fschuch** [comment]
These parameters control the points used as a reference for the lagrangian interpolator. npif represents how many points will be in the fluid side while izap allows skipping the first point at the interface, it avoids instability in some cases.
