### ISSUE TITLE
Calculation of  ux, uy, uz in IBM

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [xcompact3d/Incompact3d#17]
Hi everyone,

Greetings. I am trying to understand the implementation of the IBM, I have few questions regarding this.

Q1. "u" is defined differently-

In the new version "u" is defined as.
real(mytype),dimension(xsize(1),xsize(2),xsize(3)) :: u
In the old version "u" is defined as.
real(mytype),dimension(xsize(1),xstart(2):xend(2),xstart(3):xend(3)) :: u

in the subroutine lagpol*(u), are they representing the same size of the array? is it possible to define the array by (nx,ny,nz)?

Q2. How are these parameters defined? Why I need these?
#npif# The highest number of fluid-points at each boundary (0, 1, 2 or 3)
#izap# First fluid-point jump ? (0: no, 1: yes=advised)

Q3. What are steps/ways I should take/follow to understand the IBM implementation?

Any suggestions, help, guidelines will be highly appreciated.

Best Regards,
Rubel Chandra Das.

**Comment by fschuch** [comment]
Dear Rubel,

A1: Both dimensions represent the same array size, the difference is only in the array index (local in the pencil or global, please take a look at [2DECOMP](http://www.2decomp.org/decomp_api.html) for more information). 

A2-3: Take a look at Gautier, R., S. Laizet, and E. Lamballais (2014), A DNS study of jet control with microjets using an immersed boundary method, International Journal of Computational Fluid Dynamics, 28(6-10), 393–410.

Please, let we know if you have more questions.

Best regards,
Felipe.
