### ISSUE TITLE
Query about the output pressure

### ISSUE THREAD

**Issue by mattfalcone1997** [xcompact3d/Incompact3d#171]
Hi,

I have a question relating to the pressure output in the visualisation subroutines.  In particular, this relates to the pressure that is output compared with the physical pressure. This may be a misunderstanding on my part, but Kim and Moin (1985) states that $p = \phi + (\Delta t/2Re)\nabla^2 \phi$, and I believe the last bit comes from the use of the Crank-Nicolson Scheme in their paper. As a result, I was wondering if Xcompact3D takes the last part into account (or if it needs to) when outputting the pressure when implicit time schemes are used for the $y$ viscous terms. 

Thanks in advance,
Matthew

**Comment by mathrack** [comment]
Hello,

I think you are correct. With the implicit time scheme for the y viscous term, one gets : 
$p = \phi + \frac{\Delta t}{2 Re} \partial_{yy} \phi$ when using Crank-Nicolson
and $p = \phi + \frac{\Delta t}{Re} \partial_{yy} \phi$ when using implicit Euler

**Comment by mattfalcone1997** [comment]
Hi,

Thanks for your response. I was wondering whether this would subsequently require modification of the visualisation so that the pressure in the binary file corresponds to the physical pressure. This is also relevant for the statistics.

**Comment by mathrack** [comment]
This definition of the pressure is selected so that when summing prediction and correction and inserting $p$ instead of $\phi$, the predicted velocity does not appear in the viscous term.

Regarding the exact meaning of physical pressure in the framework of incompressible flows, ...

**Comment by mattfalcone1997** [comment]
I am only concerned with whether the pressure output in postprocessing should be modified to account for the implicit scheme. I do not believe that this is done at the moment (it seems that $\phi$ is output rather than $p$, although I may be wrong).

**Comment by mathrack** [comment]
The current code outputs $\phi$ and not $p$ when using the implicit scheme.

**Comment by mattfalcone1997** [comment]
Okay, thanks for the clarification. Is this something that should/will be updated at a future point? I am not sure how important this is as the difference is $O(\Delta t)$.

**Comment by mathrack** [comment]
I am not planning to open a PR for this modification. The estimation of $\partial_{yy} \phi$ could be inserted just before the call to `transpose_y_to_x` : https://github.com/xcompact3d/Incompact3d/blob/master/src/visu.f90#L245

**Comment by mattfalcone1997** [comment]
Thanks for your help. I may have a play around with this. I am happy to close this now.
