### ISSUE TITLE
Forcing term (IBM)

### ISSUE THREAD

**Issue by Xixiong-Guo** [xcompact3d/Incompact3d#18]
Hi all,

When applying IBM module (old school IBM), the direct forcing term is calculated based on Eq.10 in ref. [Laizet S. & Lamballais E., 2009, High-order compact schemes for incompressible flows: a simple and efficient method with the quasi-spectral accuracy, J. Comp. Phys. ].

I am unable to find out the calculation lines of RHS in Eq.10 in the code. Could anyone point out where is it ? Or how can I output the direct forcing term f ?

Thanks.

Xixiong

**Comment by xcompact3duser** [comment]
The forcing term in Incompact3d is used to prescribe a targeted velocity inside a solid geometry (the simplest forcing is to impose a zero velocity). I am not quite sure what you mean by calculating the RHS in Eq.10? This equation is never explicitly calculated in the fractional step method used in Incompact3d.

Best wishes,

Sylvain

**Comment by jxgxx** [comment]
Thanks.
But I am still in puzzle. From Eqs. 3-5,  the "f^~" must be a known term, in order to obtain u_k+1 from k time step. Then how to make it works without knowing the "f^~" (together with eq.10) ?

**Comment by jxgxx** [comment]
Thanks.
But I am still in puzzle. From Eqs. 3-5, the "f"  must be a known term, in order to obtain u_k+1 from k time step. Then how to make it works without knowing the "f" (together with eq.10) ?
