### ISSUE TITLE
Error while compiling Xcompact3D in HPC

### ISSUE THREAD

**Issue by gauravity30** [xcompact3d/Incompact3d#196]
I am tying to run a simulation in our HPC. I am not able to compile the code.  I get the error `function 'is_contiguous' at (1) has no implicit type` in decomp2d/io.f90 file. The function is_contigous is not defined anywhere in the file. Interestingly, I didn't face this error when I compiled the code on my Laptop (Ubuntu). 

1. Git cloned the latest version (commit #4949f03).
2. Ran `module load compiler/openmpi/3.1.0/gnu`, then `make clean` and `make` to compile.

As I mentioned earlier, I didn't face this error while compiling the code in my laptop. But facing the error while compiling it on the HPC.

![Screenshot 2023-06-13 083627](https://github.com/xcompact3d/Incompact3d/assets/53783610/49192586-bd95-4e05-8053-d89119f0079c)

**Comment by mathrack** [comment]
Hello,

The statement `IS_CONTIGUOUS` is a standard 2008 Fortran statement. Please use a compiler that supports F2008.
https://gcc.gnu.org/onlinedocs/gfortran/IS_005fCONTIGUOUS.html

Best,
Mathrack

**Comment by gauravity30** [comment]
It compiled when i commented those two lines. Is there any issue if comment them ? There were attached comments "safety check" with those lines.

**Comment by mathrack** [comment]
Remove safety checks at your own risk.

**Comment by gauravity30** [comment]
Okay, thanks !

**Comment by gauravity30** [comment]
I checked the version of openmpi and gfortran in our HPC. 
We have openmpi version 4.0.1, 4.0.2 and 4.1.4 and gfortran version 4.8.5 and 8.0.3 respectively. The problem still persists. I am still getting the is_contiguous error.

**Comment by mathrack** [comment]
Hello, recent versions of the gnu Fortran compiler can compile the code. I do not have a detailed list of all the supported versions of the GNU compiler. Please note that we do not provide support for such cluster-specific details.

[The `is_contiguous` intrinsic has been implemented on 2019-01-07.](https://gcc.gnu.org/wiki/Fortran2008Status)

**Comment by pbartholomew08** [comment]
According to this https://gcc.gnu.org/wiki/Fortran2008Status the `is_contiguous` intrinsic was probably implemented somewhere between gfortran v8.2 and v8.3 (see dates at https://www.gnu.org/software/gcc/releases.html)

**Comment by pbartholomew08** [comment]
I would recommend updating the gfortran installation if possible

**Comment by gauravity30** [comment]
Okay, sure. I will try updating the gfortran version.
