### ISSUE TITLE
Suggestion Readme file

### ISSUE THREAD

**Issue by shykafer** [xcompact3d/Incompact3d#20]
Hey Guys, 

just a hint for the Readme file. 
In there you recommend to use incompact3d version 2.0, which I followed and then I was trying to run the BC-Channel-flow.prm settings just as I found them in this version (with istret=2). Unfortunately, the flow field will immedeately diverge after a few timesteps. After some time I realised, that the stretching function for istret = 2 had an mistake you fixed in a later version. 

So it might be better to change the BC-Channel-flow.prm settings or write a hint, that the Channel-flow with istret=2 is not working or one should use your fix in commit 476e5f8e682c5f803451a4245fda66504b8514e6 . 

Thanks a lot for your work!

**Comment by ricardofrantz** [comment]
Thanks for the hint! It is fixed and working!
