### ISSUE TITLE
The simulation terminates automatically without any divergence.

### ISSUE THREAD

**Issue by gauravity30** [xcompact3d/Incompact3d#200]
I am testing a cylinder-case simulation with 2 cores on laptop before I run it on the HPC using 200 cores (100x2) for any divergence issues. But the code is terminating on its own. I get the following error.

--------------------------------------------------------------------------
`Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.`
--------------------------------------------------------------------------
--------------------------------------------------------------------------
`mpirun noticed that process rank 0 with PID 0 on node gauravVostro exited on signal 9 (Killed).`
--------------------------------------------------------------------------

I used the command `mpirun -np 2 xcompact3d`. I have tried with mesh size 800x800x16 and 900x900x16. Both produce the same error. I have tried lowering the time-step. But same issue. I have attached the input.i3d file. Please help me on this error.

[inputi3d.txt](https://github.com/xcompact3d/Incompact3d/files/11915507/inputi3d.txt)

**Comment by pbartholomew08** [comment]
Without more information about where it exits I think your issue is likely due to the mesh. You should aim to use combinations of powers of 2 (adding 1 for non-periodic directions), for example using BCs 2-0-0 a mesh of 769x768x16 would be fairly close to your desired resolution and should work.

I don't think this is in fact a bug so will close, if suggested solution doesn't work please open a question in the Discussion section.

**Comment by gauravity30** [comment]
Okay, thanks ! Earlier I ran a simulation on my HPC with 200 cores (100x2) and 750x750x16. The simulation ran for 50000 timesteps out of 120000 and then terminated on it own. I have attached a screenshot of the error. After going through the issues on github I found someone faced the same error (issue 141) I faced, so it was suggested that the NXM, NYM, NZM / p_row, p_col should be integers. So, I was trying for the mesh sizes.

The error I got on HPC.
![image](https://github.com/xcompact3d/Incompact3d/assets/53783610/2e77d550-2961-4bcf-b5dc-c33d5ddd8a3a)

Also, can you elaborate more on how did you choose the mesh size particular mesh size ?

**Comment by pbartholomew08** [comment]
OK, that is possibly a bug occurring when it writes a restart file.

I chose the mesh size by combining two numbers that are a power of 2 (768 = 512 + 256), because of how the discretisation works you need to add 1 to this number of points when using a non-periodic boundary condition.

**Comment by pbartholomew08** [comment]
When it fails on your laptop is it the same as above? Based on this and your `input.i3d` file it is failing when you do a restart, but must have already performed 4 restarts.

**Comment by gauravity30** [comment]
On my laptop it is not even starting. I also tried with 769 x 768 x 16 but the same issue as earlier.

**Comment by pbartholomew08** [comment]
So it immediately crashes, the first thing it prints is `mpirun detected an error...`?

**Comment by gauravity30** [comment]
Yup. 
![image](https://github.com/xcompact3d/Incompact3d/assets/53783610/5927af44-da84-4f49-868f-09813eab1892)

**Comment by pbartholomew08** [comment]
So no, that's not the first thing that happens it seems like it goes wrong somewhere in the geometry generation. Are you using the same compilers between the HPC and your laptop? Can you try building with
```
make BUILD=debug
```
assuming you're using `gfortran` this should detect floating point errors.

Have you changed the Cylinder case at all?

**Comment by gauravity30** [comment]
No, the compiler in HPC is little older than my laptop. On HPC, we have `gfortran 10.2.0` and on my laptop I have `11.3.0`. I haven't changed the bc_cylinder.f90 file. I am just using the stock files.

**Comment by pbartholomew08** [comment]
Other than the mesh size then this should work. Which version of the code are you using? Can you try the latest?

**Comment by gauravity30** [comment]
I am using the latest version of xcompact3D expect for the latest commit yesterday.

**Comment by pbartholomew08** [comment]
I'm afraid I can't reproduce this locally. When I run
```
mpirun -np 4 /path/to/xcompact3d /path/to/examples/Cylinder/input_DNS300_LR.i3d
```
either with the default grid or the `769x768x16` I am able to atleast begin iterating without the errors you report. Please try using this input file and if you still run into problems open a discussion, I don't believe this is a bug.

**Comment by gauravity30** [comment]
Okay, I tried on a different PC. I am not getting the mpi error. I think something is wrong with my Ubuntu or it is not able to handle the load. Anyways thanks for the tip on setting up the mesh. I will try the simulation on my HPC with the new mesh size.
