### ISSUE TITLE
Verification of restart can crash the simulation

### ISSUE THREAD

**Issue by gauravity30** [xcompact3d/Incompact3d#204]
I am running a cylinder case simulation on our HPC with 200 cores. The first time I ran simulation with 750x750x16 on 100x20 cores. The simulation also temrinated after running 40000 time-steps out of 120000. Going through the issue number #141, I  modified the mesh to 1041 x 1040 x 20 with 20 x 10 cores based on the suggestions. This time also the simulation terminated at 70000 steps out of 600000.  I believe there is some bug which is causing the simulation to crash at restart-points. 
The error I got,
![image](https://github.com/xcompact3d/Incompact3d/assets/53783610/69ec48a4-4ffe-402d-bdf2-edee09021a3c)

I am using openmpi 4.0.2 and gfortran 10.2.0 to compile and run the simulation. I have attached the input.i3d file.
[inputi3d.txt](https://github.com/xcompact3d/Incompact3d/files/11929394/inputi3d.txt)

**Comment by mathrack** [comment]
Hello,

This is probably related to some subroutines associated with the "validation" of restart files. Try to avoid the subroutines `rename`and `delete_filedir`, they are moving or deleting stuff and this might cause your issue.

I would suggest to modify the file `tools.f90` as follows :

- Comment the call to `rename` here https://github.com/xcompact3d/Incompact3d/blob/master/src/tools.f90#L255
- Replace the if condition returned by `validate_restart` with `.true.` https://github.com/xcompact3d/Incompact3d/blob/master/src/tools.f90#L318
- Comment the call to `delete_filedir` here https://github.com/xcompact3d/Incompact3d/blob/master/src/tools.f90#L319

Cheers,
Mathrack

**Comment by mathrack** [comment]
@pbartholomew08 if it is important to keep this validation step, we could make it optional

**Comment by gauravity30** [comment]
Okay I will check whether the issue is being resolved by the method. Thanks for the help !

**Comment by gauravity30** [comment]
@mathrack Can you verify the changes you recommended ? It will be a great help. 

`       if (adios2_restart_initialised) then`
`          ! First, rename old checkpoint in case of error`
`          !call rename(resfile, resfile_old) !L255`
`       end if`
`    end if
`

`
! Validate restart file then remove old file and update restart.info`
`if (.true.) then !L318`
`          !call delete_filedir(resfile_old) !L319`
`          ! Write info file for restart - Kay SchÃ¤fer`

**Comment by gauravity30** [comment]
@mathrack Thanks, I think the solution is working. My simulation is running for past 9 hrs without terminating. I will let you know the final results.

**Comment by mathrack** [comment]
Thank you for the update

**Comment by gauravity30** [comment]
@mathrack The 48hrs of simulation has completed without terminating. Thanks for the tip ! Great help. I think we can close the issue.

**Comment by mathrack** [comment]
Thank you for the feedback. I will re-open. I think the issue should remain open until we have made the verification of restart files optional.

Switching from bug to enhancement because this was not reported by other users.

**Comment by gauravity30** [comment]
Sure, thanks !
