### ISSUE TITLE
Issues with dynamic Smagorinsky model

### ISSUE THREAD

**Issue by yeechin** [xcompact3d/Incompact3d#205]
I want to report two issues regarding the dynamic Smagorinsky model for you to consider.

1. By default, the max dynamic Smagorinsky constant (maxdsmagcst) by is set to zero. If it is not specified in the input file, then the calculated turbulent viscosity would be zero throughout the computational domain, and thus the invalidate the les model. I suggest to use a relative larger number as default value for maxdsmagcst, say 0.14.
2. The variables sxx1, syy1, szz1, sxy1, syz1 and sxz1 are not calculated before their use on line 615 of the file les_models.f90. Though their values are updated later on line 866 in the same subroutine by "call smag(nut1,ux1,uy1,uz1)", their value updates are lagged. A specific problem is that if the dynamic Smagorinsky model is adopted and if you are at the first step of the simulation, sxx1, syy1, szz1, sxy1, syz1 and sxz1 will always be zero. I suggest to move line 866 before line 615, which should be able to solve the problem.

**Comment by slaizet** [comment]
issues fixed and tested on the TGV case.
