### ISSUE TITLE
Typo in init_xcompact3d subroutine

### ISSUE THREAD

**Issue by gauravity30** [xcompact3d/Incompact3d#212]
Hello,
I think there is a typo in the `init_xcompact3d` subroutine in `xcomapact3d.f90`.  `genepsi3d` and `body` both the subroutines are being called for `iibm==3`. Although, it doesn't matter much, since `genepsi3d` will be called always. 

```
  if ((iibm.eq.2).or.(iibm.eq.3)) then
     call genepsi3d(ep1)
  else if ((iibm.eq.1).or.(iibm.eq.3)) then
     call body(ux1,uy1,uz1,ep1)
  endif
```
https://github.com/xcompact3d/Incompact3d/blob/a0bec26fdb5a002cfe351e3a398028aa0c93a35f/src/xcompact3d.f90#L235C2-L239

**Comment by slaizet** [comment]
problem fixed
