### ISSUE TITLE
BC-Pipe-flow.f90 not included in src/CMakeLists.txt

### ISSUE THREAD

**Issue by CFD-Xing** [xcompact3d/Incompact3d#222]
**Describe the bug**
Compilation of the master branch (commit 34d69d2170bc172faafbdf80f697298ad9e89d0a) results in the following compilation error: 
![compilation_error](https://github.com/xcompact3d/Incompact3d/assets/101667766/2ac5eee1-717c-429a-bb95-2934383ab3c6)

This error is caused be the fact that `BC-Pipe-flow.f90` was not included in the src/CMakeLists.txt file (probably just forgotten during last commit). Adding `BC-Pipe-flow.f90` to the CMakeLists.txt file fix the problem

![bugfix](https://github.com/xcompact3d/Incompact3d/assets/101667766/777532ee-09c6-4e7c-8ba5-ebe9480aa492)

**Comment by mathrack** [comment]
Hello,

I think you have identified the issue and a fix. Please open a pull request.

Thank you

**Comment by CFD-Xing** [comment]
@mathrack Thanks for your reply. I am not a contributor to Incompact3d, so I doubt that I have permissions to push commit...

**Comment by mathrack** [comment]
You can fork and push a commit in your fork (in master branch or in a dedicated branch). You can then open a PR from the branch in your fork against master branch here. If it appears painful, just let me know and one of the developers will open a PR.

Cheers
