### ISSUE TITLE
How to use variables from other threads?

### ISSUE THREAD

**Issue by jxgxx** [xcompact3d/Incompact3d#23]
Hi all,

Maybe this question is not directly related to Incompact3d itself, but please allow me to ask here.

In Incompact3d, how can I use ux1 from all threads freely under a specific thread?  As far as I know, I need to use MPI_Allgather, but I don't know the details about this function.

For example, if I use 2*2=4 threads, total domain is (100*80*60), so each thread is (100*40*30). If I want to calculate a new variable at the beginning of condiff.f90, say ux*= ux1(80,25,25)  /!nrank=0/  + ux1(20,10,10)  /!nrank=1/ + ...  other ux1 from other nrank #. 

I think I need to gather all ux1 first, and what I've done was that:
 call MPI_gather(ux1, nvect1, real_type, ux1star, 4*nvect1, real_type, MPI_COMM_WORLD, ierror)
Here, ux1star is the new 3D array I collect ux1 from all threads, so its size is 4 times of each thread nvect1. But it doesn't work.

Any advice on this issue? Thanks in advance.

**Comment by fschuch** [comment]
Hello,

I suggest you make the sum individually on each pencil and then use MPI_REDUCE or MPI_ALLREDUCE. You can find some examples in the code or at [mpitutorial.com](http://mpitutorial.com/tutorials/mpi-reduce-and-allreduce/). The MPI_GATHER for the entire 3D domain will produce a bottleneck and reduce the parallel efficiency.
