### ISSUE TITLE
Incorrect boundary conditions for immersed solids in z direction

### ISSUE THREAD

**Issue by adfboyd** [xcompact3d/Incompact3d#235]
**Describe the bug**
When attempting to simulate immersed objects with z normals, the calculated z boundaries of the solid are off by a factor of the parameter nraf - for example when I attempt to simulate a box with boundaries [2.5,3.5],[2.5,3.5],[2.5,3.5], the values stored in xi(),xf() etc are [2.5,3.5],[2.5,3.5],[0.25,0.35] if nraf = 10, or [2.5,3.5],[2.5,3.5],[1.25,1.75] if nraf = 2. (I printed these out when they are called in cubsplx, cubsply, cubsplz - in ibm.f90) I only caught this because these incorrect values lead to index bounds errors later in the code. Of course, if nraf=1 then the problem does not manifest, but I have a very coarse boundary which I would like to be able to improve. I have confirmed that the calculation of the epsi field is correct by visualising it directly - it behaves as it should.
It seems clear that there is a missing multiple of nraf somewhere in the z calculation, but I have been unable to find any inconsistencies. 

**To Reproduce**

This can be replicated just be replacing the setup in BC-Cylinder.f90 with a different shape function and then running the stock input file with iibm=3. I have attached both files that will replicate the error. It works on the most current version of Incompact3d.

1. Git version - Current.
2. Just using the default "make BUILD=debug" on my ubuntu machine.
3. I've attached the only changes I've made, as well as the input file.

**Expected behavior**
The program should run without issue (infact if you run with all optimisations, sometimes the bounds error doesn't seem to cause any major issues, and the solutions look ok).

I've attached a screenshot of the readouts that confirmed what I have so far.
<img width="440" alt="Screenshot 2023-11-03 124005" src="https://github.com/xcompact3d/Incompact3d/assets/61464721/97610bf2-66ed-48f4-9790-4ef3c3833bbf">
[BC-Cylinder.f90.txt](https://github.com/xcompact3d/Incompact3d/files/13250292/BC-Cylinder.f90.txt)
[input.i3d.txt](https://github.com/xcompact3d/Incompact3d/files/13250293/input.i3d.txt)

Thank you very much for your time.

**Comment by slaizet** [comment]
Hi,
We are going to look into this, thanks.
Cheers,
Sylvain

**Comment by adfboyd** [comment]
Hi Sylvain,

Thanks for your response - I've actually just figured out the issue - I wasn't including dz as an input in the geomcomplex_cyl() subroutine - adding this and then updating the call of the subroutine in geomcomplex() fixes my issue. (I'm surprised that adding dz worked at all without this - as far as I can tell dz shouldn't be in scope but I guess it is!)
Apologies for what turned out to be a simple error on my part!

Best wishes,
Andrew
________________________________
