### ISSUE TITLE
Is it possible to implement inflow and outflow BC in the channel flow type? 

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [xcompact3d/Incompact3d#24]
Hi everyone,

I am trying to implement inflow and outflow BC in the channel flow type. I included the inflow and outflow subroutine in the BC-Channel.f90 file. Also, I changed the initial profile to poiseuille profile in the inflow subroutine. I used AB3 time scheme and didn't use a stretched grid. In summary, I tried to merge channel and cylinder flow type, but unfortunately, it didn't work.

Any help or suggestions are highly appreciated.

Best Regards,
Rubel Chandra Das.

**Comment by fschuch** [comment]
Dear Rubel,

Can you attract your BC files or be more specific about why it is not working?

**Comment by RUBEL-CHANDRA-DAS** [comment]
Hi Felipe N. Schuch,

Thank you for your reply. I am sorry that I forgot to reply to your question. The inflow and outflow work fine. I made a silly mistake back then.

I'll really appreciate if you can help me on this - https://github.com/xcompact3d/Incompact3d/issues/25

Best Regards,
Rubel Chandra Das.
