### ISSUE TITLE
compile error with ADIOS2 support on

### ISSUE THREAD

**Issue by ningli-amd** [xcompact3d/Incompact3d#243]
**Describe the bug**

There is a compiling error when ADIOS2 support is switched on. This applies to both v4.0 and the latest master branch.

```
mpif90 -cpp -O3 -funroll-loops -floop-optimize -g -Warray-bounds -fcray-pointer -fbacktrace -ffree-line-length-none -fallow-argument-mismatch -DADIOS2 -I./src -I./decomp2d -cpp -O3 -funroll-loops -floop-optimize -g -Warray-bounds -fcray-pointer -fbacktrace -ffree-line-length-none -fallow-argument-mismatch -DDOUBLE_PREC -DVERSION=\"v4.0-249-g8d7b078\"   -DADIOS2_USE_MPI -I/path/to/adios2/include/adios2/fortran   -c decomp2d/io.f90
decomp2d/io.f90:139:87:

  139 |   call adios2_init(adios, trim(config_file), MPI_COMM_WORLD, adios2_debug_mode, ierror)
      |                                                                                       1
Error: There is no specific subroutine for the generic 'adios2_init' at (1)
make: *** [Makefile:110: decomp2d/io.o] Error 1
```

**To Reproduce**

make IO=adios2 ADIOS2DIR=/path/to/adios2 #with MPI wrapper in $PATH

**Comment by pbartholomew08** [comment]
Can I check - you are using ADIOS2 v2.9 or later? They have deprecated this interface and I need to update it, thanks for catching.

**Comment by ningli-amd** [comment]
I was using ADIOS2 2.9.1

**Comment by pbartholomew08** [comment]
I don't have a v2.9 ADIOS2 install around to check right now, but the commit on the associated branch should resolve this if you would like to try (it is backwards compatible to compile with my local v2.8 build).
