### ISSUE TITLE
runtime error with Intel ifx compiler

### ISSUE THREAD

**Issue by ningli-amd** [xcompact3d/Incompact3d#247]
**Describe the bug**

This is from a debug build with the Intel OneAPI ifx compiler. While running the standard channel flow case, I pick up the following error at the beginning of the code:
```
forrtl: severe (189): LHS and RHS of an assignment statement have incompatible types
Image              PC                Routine            Line        Source
xcompact3d         000000000278A0AF  Unknown               Unknown  Unknown
xcompact3d         000000000043084B  alloc_x_real               32  alloc.inc
xcompact3d         00000000004595A9  init_variables            141  variables.f90
xcompact3d         000000000079E3B9  init_xcompact3d           211  xcompact3d.f90
xcompact3d         000000000079DBB9  init_xcompact3d_.           0  xcompact3d.f90
xcompact3d         000000000079D228  xcompact3d                 51  xcompact3d.f90
xcompact3d         000000000040F74D  Unknown               Unknown  Unknown
libc-2.28.so       00001462526A5D85  __libc_start_main     Unknown  Unknown
xcompact3d         000000000040F66E  Unknown               Unknown  Unknown
```
This is the v4.0 code.

**Comment by mathrack** [comment]
Hello, thank you for reporting this issue. The bug seems to occur when the `decomp_info` object is copied. Could you try the branch [merge_2decomp_main](https://github.com/xcompact3d/Incompact3d/tree/merge_2decomp_main) to check if the bug is present there ?

I have merged the branch `main` of 2decomp inside xcompact3d. The copy of the `decomp_info` object is no longer present.

**Comment by slaizet** [comment]
Hi Ning,
May I ask you if you use cmake or Makefile to compile the code, which ifx version did you use and which MPI library did you use?
Cheers,
Sylvain

**Comment by ningli-amd** [comment]
Hi Sylvain,
I was built the package using the Makefile approach and with the MKL FFT engine and OpenMPI. The ifx is from OneAPI v2023.2.

**Comment by ningli-amd** [comment]
I can confirm that branch `merge_2decomp_main` does fix the runtime issue.
