### ISSUE TITLE
How to Implement Recycling Technique?

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [xcompact3d/Incompact3d#25]
Hi Everyone,

Greetings! I am trying to implement the recycling technique to generate turbulence. But I am not getting the desired results. 

I am taking one plane of data from downstream and put them in the inflow plane. I am posting the part of the code I changed for recycling purpose. I called the "recycling subroutine" instead of the "inflow subroutine".

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine recycle (ux,uy,uz,phi)

  USE param
  USE variables
  USE decomp_2d

  implicit none

  integer  :: i,j,k,is
  real(mytype),dimension(xsize(1),xsize(2),xsize(3)) :: ux,uy,uz
  real(mytype),dimension(xsize(1),xsize(2),xsize(3),nphi) :: phi

  do k=1,xsize(3)
     do j=1,xsize(2)
        do i=1,xsize(1)
           ux11(i+xstart(1)-1,j+xstart(2)-1,k+xstart(3)-1)=ux(i,j,k) 
           uy11(i+xstart(1)-1,j+xstart(2)-1,k+xstart(3)-1)=uy(i,j,k)
           uz11(i+xstart(1)-1,j+xstart(2)-1,k+xstart(3)-1)=uz(i,j,k)
        enddo
     enddo    
  enddo

  do k=1,xsize(3)
     do j=1,xsize(2)
        bxx1(j,k)=ux11(128,j+xstart(2)-1,k+xstart(3)-1)
        bxy1(j,k)=uy11(128,j+xstart(2)-1,k+xstart(3)-1)
        bxz1(j,k)=uz11(128,j+xstart(2)-1,k+xstart(3)-1)
     enddo
  enddo

  return
end subroutine recycle
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I defined the ux11,uy11,uz11 in "module variables" as
   real(mytype), save, allocatable, dimension(:,:,:) :: ux11,uy11,uz11
And allocated in the "var module" as
    allocate(ux11(xstart(1):xend(1),xstart(2):xend(2),xstart(3):xend(3))) 
    allocate(uy11(xstart(1):xend(1),xstart(2):xend(2),xstart(3):xend(3))) 
    allocate(uz11(xstart(1):xend(1),xstart(2):xend(2),xstart(3):xend(3))) 

Please let me know if someone has any advice or suggestions regarding recycling implementation, I appreciate your time.

Thank you,
Rubel Chandra Das.

**Comment by ricardofrantz** [comment]
This is weird. I would recommend you to implement this inside the `subroutine boundary_conditions (ux,uy,uz,phi,ep1)`, where the bxx1,bxy1,bxz1 planes are already defined and will be superimposed at the inlet if you use nclx1=2. 

It seems you are trying to do this:

```
  do k=1,xsize(3)
     do j=1,xsize(2)
        bxx1(j,k)=ux(128,j,k)
        bxy1(j,k)=uy(128,j,k)
        bxz1(j,k)=uz(128,j,k)
     enddo
  enddo
```

Just copy and paste in the boundary_conditions subroutine. Then you need to define an outflow condition. Have a look [here](https://github.com/xcompact3d/Incompact3d/blob/fe9d09ba2de0dcec26c81e50e87c0fb8c674ef66/BC-Cylinder.f90#L199).

R.

**Comment by RUBEL-CHANDRA-DAS** [comment]
Hi Ricardo Frantz,

Thank you for your suggestion, I did try your way. But I am getting the same results. I am attaching six screenshots of the contour and Q-criterion at 0 secs, 100 secs, and 200 secs respectively.

I am trying to simulate turbulent boundary layer flow using recycling technique. I am attaching the BC-Cylinder.f90 file, where I initialized the boundary layer in the "init subroutine".

Please tell me what I am doing wrong or what is the right way to simulate turbulent boundary layer using recycling technique. Thank you for your valuable time.

Best Regards,
Rubel Chandra Das.

![s_0sec](https://user-images.githubusercontent.com/39419978/42489844-ab82de9c-83ca-11e8-9c13-14b8d8058746.png)
![s_100sec](https://user-images.githubusercontent.com/39419978/42489845-ab9994ca-83ca-11e8-856d-bd65ccfd2518.png)
![s_200sec](https://user-images.githubusercontent.com/39419978/42489846-abb36e18-83ca-11e8-9f29-9b163b8471a3.png)
![q_0sec](https://user-images.githubusercontent.com/39419978/42489851-b664ae80-83ca-11e8-9dfa-1b03b77baef2.png)
![q_100sec](https://user-images.githubusercontent.com/39419978/42489853-ba31b666-83ca-11e8-9457-4cd181d458d8.png)
![q_200sec](https://user-images.githubusercontent.com/39419978/42489854-bcdaa72e-83ca-11e8-8e34-139890fcffb7.png)
[BC-Cylinder.txt](https://github.com/xcompact3d/Incompact3d/files/2178866/BC-Cylinder.txt)

**Comment by RUBEL-CHANDRA-DAS** [comment]
Hi Felipe N. Schuch,

Sorry for late response as I was running some cases using your suggestions with little changes in domain size and the number of grid points. But the sad news is that I am getting results similar to before.

At first, I took the recycling plane at (nx-1)/8, then at (nx-1)/4, eventually at  (nx-1)/2 as the first two cases were taking too much time to make the flow turbulent.

The code runs fine for 285 seconds, then blows up. I am attaching the files and some pictures. The first image is at 285 sec, the second one is Q-criterion at 285 sec. The third and fourth images are log file at the initial time and last time (before the code blows up).

From the log file, you can see that both inflow and outflow flow rates are decreasing leading to negative values eventually (I don't know for sure the reasons for that, is mass conservation has something to do with that?), this could be why recycling is not working. Also, the outflow velocity becomes negative as the time progresses.

When you said that the code runs fine, did you got a turbulent boundary layer flow? I am really struck by this recycling, can you suggest something that I can work to fix the this. 

I appreciate your valuable time, thank you. Have a good day.

Best Regards,
Rubel Chandra Das.

![285secs](https://user-images.githubusercontent.com/39419978/42793413-4b95d242-8937-11e8-9ecd-e66025d7f379.png)
![285secq](https://user-images.githubusercontent.com/39419978/42793422-4feae814-8937-11e8-865b-083e2c0c7599.png)
![output_first](https://user-images.githubusercontent.com/39419978/42793447-63293c46-8937-11e8-9703-96e55a08f771.png)

![last_output](https://user-images.githubusercontent.com/39419978/42793434-59bc9e64-8937-11e8-9967-6660f259319c.png)
[BC-Cylinder.tar.gz](https://github.com/xcompact3d/Incompact3d/files/2199939/BC-Cylinder.tar.gz)

**Comment by fschuch** [comment]
Dear Rubel,

I tested the recycling technique just visually on Paraview, since I can not run it for enough time. 

I am wondering if this technique will work in this configuration, because the turbulent boundary layer grows in Y-direction, and at some point, it kills the code.

FS.

**Comment by ricardofrantz** [comment]
Dear @RUBEL-CHANDRA-DAS, any update on the topic?
Ricardo

**Comment by RUBEL-CHANDRA-DAS** [comment]
Dear @ricardofrantz, I couldn't make any further progress on the topic, which led to dropping the project I was working on.

Rubel
