### ISSUE TITLE
Using Periodic B.C. with Alternating Forcing Direction IBM gives error

### ISSUE THREAD

**Issue by gauravity30** [xcompact3d/Incompact3d#255]
The paper titled "A simple and scalable immersed boundary method for high-fidelity simulations of fixed and moving objects on a Cartesian mesh" mentions the use of periodic boundary condition in y-direction along with stretching.

Extract from the paper,
`A resolution of nx × ny = 385 × 384 is used, with a stretched mesh in the vertical direction towards the centre of the domain with the smallest mesh spacing being ymin = 0.04`. Initial conditions are the same as in the previous section except for the boundary conditions. A uniform velocity u∞ = 1.0 is imposed at the inlet while a 1D-convection equation is imposed at the outlet. `Periodic boundary conditions are imposed in the vertical direction.`

But when setting the case using the examples input.i3d with the following values of the parameters,
```
nx=301               ! X-direction nodes
ny=301                 ! Y-direction nodes
nz=8                 ! Z-direction nodes
istret = 1            ! y mesh refinement (0:no, 1:center, 2:both sides, 3:bottom)
beta = 0.259065151    ! Refinement parameter (beta)

! Domain
xlx = 16.      ! Lx (Size of the box in x-direction)
yly = 16.            ! Ly (Size of the box in y-direction)
zlz = 2.            ! Lz (Size of the box in z-direction)

! Boundary conditions
nclx1 = 2
nclxn = 2
ncly1 = 0
nclyn = 0
nclz1 = 0
nclzn = 0

iibm = 3.
```

I get the following error, 
![image](https://github.com/xcompact3d/Incompact3d/assets/53783610/48a5c594-02ad-4a65-bd55-674322334e43)

Is this a bug or whether it needs to be implemented manually ?

**Comment by slaizet** [comment]
Hi,

This specific set-up was obtained with a 2D version of Xcompact3d that is not open-source. We are aiming at allowing stretching features with periodic boundary conditions in the current main branch of Xcompact3d, hopefully in the next few months or so.

You can run those simulations with the current main branch with free-slip boundary conditions in the Y direction (I just did it using `input_DNS300_LR_2D.i3d`, by allowing a stretched mesh, changing the boundary conditions in the Y direction, and the number of mesh nodes accordingly). 

Best,

Sylvain

PS: By looking at your input file, I can see that the number of points is not set-up properly (periodic BC needs ny=300 not 301). Also it is not clear why you are using nz=8. nz=1 is working fine for the cylinder, just use  `input_DNS300_LR_2D.i3d`.

**Comment by gauravity30** [comment]
Thank you for the reply ! 
I will look forward to the update. Thank you for the suggestions !

**Comment by gauravity30** [comment]
Hey @slaizet, 
I tried using the stretching with slip b.c. for my case flow around a flat plate and even though the y+ is less than 1, The error in CL and CD is more than 10%. Any suggestions for improvements.

Thank you for your response.
