### ISSUE TITLE
How mass conservation with the inflow/outflow method is working?

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [xcompact3d/Incompact3d#26]
Hi everyone,

I am having difficulty to understand the mass conservation with the inflow/outflow method. Can anyone please tell me how mass conservation is being satisfied with inflow and outflow. I'll really appreciate any help or suggestions regarding this.

Thank for your time,
Rubel Chandra Das.

**Comment by fschuch** [comment]
The flow rate at inflow and outflow boundaries are computed at subroutine pre_correc in [navier.f90](https://github.com/xcompact3d/Incompact3d/blob/fe9d09ba2de0dcec26c81e50e87c0fb8c674ef66/navier.f90#L427). The velocity at outflow is adjusted properly to guarantee that both are equivalent `bxxn(j,k)=bxxn(j,k)-utt+ut11` and consequently, guarantee mass conservation.
