### ISSUE TITLE
Potential issue with CMake 3.22.5 / GNU 12.3.0 / OpenMPI 5.0.3 

### ISSUE THREAD

**Issue by gauravity30** [xcompact3d/Incompact3d#270]
**Describe the bug**
The build using CMake version 3.22.5 with GNU 12.3.0 and OpenMPI 5.0.3 fails on our HPC with the following error,

```
    7 |    use mpi
      |        1
Fatal Error: Cannot read module file ‘/home/apps/openmpi/5.0.3/install/lib/mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.
gmake[5]: *** [src/CMakeFiles/decomp2d.dir/decomp_2d_constants.f90.o] Error 1
gmake[4]: *** [src/CMakeFiles/decomp2d.dir/all] Error 2
gmake[3]: *** [all] Error 2
gmake[2]: *** [downloadBuild2decomp-prefix/src/downloadBuild2decomp-stamp/downloadBuild2decomp-build] Error 2
gmake[1]: *** [CMakeFiles/downloadBuild2decomp.dir/all] Error 2
gmake: *** [all] Error 2
CMake Error at cmake/FindDECOMP2D.cmake:22 (message):
  Build step for 2decomp-fft failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:46 (find_package)
```

**To Reproduce**
1. Release Version 4.1
2. cmake -S ./incompact -B ./build

I checked the version of GNU Fortran and MPI Fortran identified by CMAKE is same i.e. 12.3.0.

```
$ which mpif90
/home/apps/openmpi/5.0.3/install/bin/mpif90

$ mpif90 --version
GNU Fortran (GCC) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gfortran --version
GNU Fortran (GCC) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Additional context**
[CMakeOutput.log](https://github.com/xcompact3d/Incompact3d/files/15438540/CMakeOutput.log)

**Comment by mathrack** [comment]
Hello,

I think you just need to export FC=mpif90 before running cmake.

Regards,
mathrack

May 24, 2024 20:21:00 Gaurav Gupta ***@***.***>:

**Comment by gauravity30** [comment]
> Hello, I think you just need to export FC=mpif90 before running cmake. Regards, mathrack May 24, 2024 20:21:00 Gaurav Gupta ***@***.***>

I tried it but no help. The issue persists.

**Comment by pbartholomew08** [comment]
Fatal Error: Cannot read module file ‘/home/apps/openmpi/5.0.3/install/lib/mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran

This implies you've changed your Fortran compiler version without rebuilding MPI

**Comment by mathrack** [comment]
I have changed the title of the issue : the latest version of the code can be compiled without issues on various HPC systems.

I think the present issue is connected with the softwares installed on a specific cluster and not with incompact3d. I will close the issue.

Feel free to comment and provide more details (build environment / build commands / ...)
