### ISSUE TITLE
Possibly there is a mistake about the dynamic Smagorinsky model, and please check

### ISSUE THREAD

**Issue by yeechin** [xcompact3d/Incompact3d#280]
**Describe the bug**
In the implementation of LES dynamic Smagorinsky model in les_models.f90 (subroutine dynsmag), first the Bij tensors are formed. But for Aij tensors, beginning at line 616
axx1 = -two * sqrt(two * (sxx1 * sxx1 + syy1 * syy1 + szz1 * szz1 + two * sxy1 * sxy1 + two * sxz1 * sxz1 + two * syz1 * syz1)) * sxx1
the axx1 is calculated from sxx1, syy1 et al. However, the arrays sxx1, syy1, szz1, sxy1, sz1 and syz1 are not calculated before line 616. The code can still possibly work, because the subroutine smag is called at line 867, which indeed calculate sxx1, syy1, szz1 arrays. However, in this way, the code is using sxx1, syy1, szz1 arrays from previous time steps. 

I think a possible solution, is to move the call of subroutine smag (line 867) to line 616, just before using sxx1, syy1, szz1 arrays to calculate axx1 arrays.

**Comment by slaizet** [comment]
Thanks we are going to look into this!

**Comment by rfj82982** [comment]
I am also looking into this since this creates issues with the Intel compiler.
