### ISSUE TITLE
Possible bug on hyperviscosity setup when using `ilesmod=0`

### ISSUE THREAD

**Issue by fvide** [xcompact3d/Incompact3d#284]
**Describe the bug**
When setting `ilesmod=0`, i.e. running DNS, the hyperviscosity parameters are set to `nu0nu=4.0` and `cnu=0.44` regardless of what was chosen in the `input.i3d` file.

This behaviour is set by this if statement: https://github.com/xcompact3d/Incompact3d/blob/8cdba7d909c90c2779bf5149161f91f854e08e9e/src/parameters.f90#L230C1-L233C8

**To Reproduce**
Steps to reproduce the behaviour:
1. Current master: [8cdba7d](https://github.com/xcompact3d/Incompact3d/commit/8cdba7d909c90c2779bf5149161f91f854e08e9e)
2. Compilation options: Default options from CMake with gcc
3. Set-up: [Explicit time channel flow](https://github.com/xcompact3d/Incompact3d/blob/master/examples/Channel/input_DNS_Re180_LR_explicittime.i3d) modified with `nu0nu=3.0` and `cnu=0.33`
4. Output to stdout: `Using the hyperviscous operator with (nu_0/nu,c_nu) = (   4.0000000000000000      ,  0.44000000000000000      )`

**Expected behavior**
`nu0nu` and `cnu` should be set to the values chosen in the `input.i3d` file.

**Comment by rfj82982** [comment]
I'll have a look in the next couple of days. I an trying to fix bug in the new release.
