### ISSUE TITLE
2D Cylinder Simulation 

### ISSUE THREAD

**Issue by mvitola** [xcompact3d/Incompact3d#29]
Hi all, 

I have download the current version of the Incompact3D. I was able to run the cylinder case in 3D. Now I am trying to change the setup to run the cylinder case in 2D, but I am getting the following error: 
BC-Cylinder.prm  post.prm  probes.prm  visu.prm

Git version        : 2.0.1-3-gfe9d09b
 
 cex, cey, ra       : (  5.00,  6.00,  0.50)
 xld, xrd, yld, yud : (  1.50,  3.50,  2.50,  2.50)

 (lx,ly,lz)=   20.000000000000000        12.000000000000000        1.0000000000000000     
 (nx,ny,nz)=         513         257           1
 (dx,dy,dz)=   3.9062500000000000E-002   4.6875000000000000E-002   1.0000000000000000     
 (nx*ny*nz)=      131841
 (p_row,p_col)=           0           0
 
 Numerical precision: Double
 Boundary condition : (nclx1 ,nclxn )=(2,2)
                      (ncly1 ,nclyn )=(1,1)
                      (nclz1 ,nclzn )=(0,0)
 High and low speed : u1=  2.00 and u2=  2.00
 Reynolds number Re :    700.00000000
 Time step dt       :      0.00050000
 Spatial scheme     :      4.00000000
                    : DNS
 Temporal scheme    : Adams-bashforth 3
 Scalar             : off
 Immersed boundary  : on with Lagrangian Poly

 Initializing variables...
 double free or corruption (out)
Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x14cdf94cf35e in ???
#1  0x14cdf94ce513 in ???
#2  0x14cdf871efaf in ???
#3  0x14cdf871ef2b in ???
#4  0x14cdf8709560 in ???
#5  0x14cdf8761926 in ???
#6  0x14cdf8767e0b in ???
#7  0x14cdf876986f in ???
#8  0x48ccca in first_derivative_
	at /home/mvitola/Projects/Incompact3d/schemes.f90:325
#9  0x48d311 in schemes_
	at /home/mvitola/Projects/Incompact3d/schemes.f90:123
#10  0x61de78 in incompact3d
	at /home/mvitola/Projects/Incompact3d/incompact3d.f90:45
#11  0x401f9c in main
	at /home/mvitola/Projects/Incompact3d/incompact3d.f90:3
Aborted (core dumped)

Is possible to adapt the 3D version to run in 2D? I am asking this because I note that in the Download page there is a 2D version of the code for cylinder simulation, but the code seems to be slightly different from the version I download using the git.

Thanks,
Marcelo

**Comment by mvitola** [comment]
Thanks Ricardo I will try it.

**Comment by mvitola** [comment]
Dear Ricardo,
I tested the quasi-2D approach you suggest using jLES=0 and nz=6 and nclz1,nclzn=0 (periodic) but the minimum value for zlz I was able to run was 0.1. Smaller value for zlz the code diverge after several time steps.

**Comment by ricardofrantz** [comment]
It sounds reasonable as this minimum delta z is related to the Reynolds and time step you're using.
