### ISSUE TITLE
Mesh Refinement for Both y and z Direction

### ISSUE THREAD

**Issue by BoqianBIT** [xcompact3d/Incompact3d#291]
I am currently conducting DNS simulations of secondary flow in a square duct, with flow along the x-direction and y and z directions perpendicular to the duct walls. 

I would like to know if the current program supports mesh refinement for both directions (e.g. y and z direction)？Or, if there are any alternative methods to simulate flow within the square duct while accurately resolving the boundary layer without excessively increasing the number of grid points?

Thank you!

**Comment by slaizet** [comment]
Mesh refinement is more than one direction is not an option because of the spectral Poisson solver.
Best,
Sylvain

**Comment by BoqianBIT** [comment]
Thanks for your reply!
