### ISSUE TITLE
IBM - Invalid memory access in special cases (iibm=3)

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/Incompact3d#294]
The present issue is specific to IBM simulations with spline reconstruction (`iibm=3`). The variable `ipol` can be used without being defined. This issue can lead to undefined behavior and out of bounds memory access.

https://github.com/xcompact3d/Incompact3d/blob/46e874e236265c2f2671f254a9e3f4415d1e40d0/src/ibm.f90#L524

The situation is similar for the variable `jpol` :

https://github.com/xcompact3d/Incompact3d/blob/46e874e236265c2f2671f254a9e3f4415d1e40d0/src/ibm.f90#L691

The situation is similar for the variable `kpol` but for some unknown reason the code is commented : 

https://github.com/xcompact3d/Incompact3d/blob/46e874e236265c2f2671f254a9e3f4415d1e40d0/src/ibm.f90#L842

Some deep review of the `iibm=3` code capability is needed. As a temporary workaround, I suggest the following : 

- Print a warning for all simulations with `iibm=3` to describe the option as experimental
- When the code is reaching the special case leading to undefined behavior, abort the simulation with an error message

**Comment by slaizet** [comment]
@mathrack would you have an input file for which you go into those special cases?

**Comment by mathrack** [comment]
Not really, catching this issue with gdd / valgrind is a bit difficult because it can change depending on the compiler and number of CPUs used...

This issue was discussed in https://github.com/xcompact3d/Incompact3d/discussions/292

I could draft a fix based on the following : https://github.com/mathrack/Incompact3d-1/tree/moving_cylinder

**Comment by slaizet** [comment]
Thanks. As far as I am concerned, I think we can comment the lines in X and Y, to be consistent with Z. I cannot workout a case with `xi(i,j,k).eq.xf(i,j,k)` (in X). Same in Y and Z.

**Comment by mathrack** [comment]
Is it possible to have something like `xi(i,j,k).eq.xf(i,j,k)` if the cylinder is moving (imposed motion for instance) and the top of the cylinder is exactly located on a node ?

**Comment by slaizet** [comment]
I will try that!

**Comment by slaizet** [comment]
okay, so still no luck in having `xi(i,j,k).eq.xf(i,j,k)` so I suggest we comment the "special case" situation in the three spatial direction. That will remove the invalid memory access.

**Comment by slaizet** [comment]
fixed with PR #316
