### ISSUE TITLE
Residual/Divergence in example Periodic Hill

### ISSUE THREAD

**Issue by shykafer** [xcompact3d/Incompact3d#30]
Hi everyone, 

I am testing the Periodic Hill example you provided here on github and wondering about the accuracy of the residual/divergence of u. I am using the same flow configuration as indicated here in Periodic-Hill.prm. 
At the moment, the simulation is at time step 100000 and at time unit of 50 and the resiudal is still about 10^-4:      DIV U  max mean=  0.3597605      4.6917202E-04
Even worse is, that the maximum Div U value is still that big. 

Could this be an issue of the new IBM version and the interplay with the fft solver? 

Thanks for your help!

**Comment by fschuch** [comment]
Hi,

It is expected for both IBM in the code (old school and Lagrangian interpolator) since the artificial velocity field inside the geometry does not necessarily follow the continuity equation (Div U = 0).

You can test it, for instance, change at `visu.prm` the variables `save_dudx`, `save_dvdy` and `save_dwdz` to `1`, then open in any visualization software (like paraview) to see the sum of them.

**Comment by shykafer** [comment]
Hi, 

thank you for your quick response! Ok, this make sense, I will try it out as soon as possible. So maybe it would be nice to have an additional information on the output to distinguish the Div U for the fluid phase and the one for the body. 

Thanks Kay

**Comment by shykafer** [comment]
Hi Felipe, 

I used the derivatives of the velocities and summed them up to get the continuity, as you mentioned. I did this in matlab and still wondering about the values. 

1. you are right. I find the highest values inside the body and one can clearly see the interface between body and fluid. But when looking for the maximum value of the continuity I get 20, but the run output said DIV U max mean= 0.3597605 4.6917202E-04. So maybe there is something wrong about how i computed the continuity? 

2. When i seperate the continuity values by the epsilon data and only average over the fluid field I get a mean continuity of about 10^-6, which is 2 orders better then the run output deliverd, but it's not machine accuracy. 

So does this mean, that in presence of a body, the IBM will reduce the order of accuracy of the solver? 

Thanks for your help
Kay

**Comment by fschuch** [comment]
Hi,

The code computes [divergence](https://github.com/xcompact3d/Incompact3d/blob/4877ceddcba208580079f0fd523ea9511f4007c4/navier.f90#L162) only in the fluid region, i.e., multiplies `ux`, `uy` and `uz` by `1-epslon` and then derivates. However, the [average](https://github.com/xcompact3d/Incompact3d/blob/4877ceddcba208580079f0fd523ea9511f4007c4/navier.f90#L210) is computed in the complete domain (fluid + solid). Notice that the divergence is computed in a partially staggered mesh, as explained in [Laizet, S., & Lamballais, E. (2009)](https://doi.org/10.1016/j.jcp.2009.05.010).

Yes, IBM reduces the order of accuracy near the body to second order when using alternating direction forcing `ivirt = 2` and first order in brutal forcing `ivirt = 1`, according to [Gautier, R., Laizet, S., & Lamballais, E. (2014)](https://doi.org/10.1080/10618562.2014.950046).

Best regards,
Felipe.

**Comment by shykafer** [comment]
Hi Felipe, 

I now see, that the way the code saves dudx, dvdy and dwdz is not the same as it computes the divergences. If you compare the both calculation, the divergence function use [interpolation functions](https://github.com/xcompact3d/Incompact3d/blob/4877ceddcba208580079f0fd523ea9511f4007c4/navier.f90#L170), while in the visu_extra subroutine there is no [interpolation](https://github.com/xcompact3d/Incompact3d/blob/4877ceddcba208580079f0fd523ea9511f4007c4/visu.f90#L270). 

So if i would like to check the divergence out of the snapshots I can't use your mentioned way by summing up the derivatives. I first have to interpolate the velocity derivatives, right? 

Thanks and best regards,
Kay

**Comment by fschuch** [comment]
Well, summing up the derivatives can give you a quick estimate. To see the exact value, you should write on disc the variable `pp3`, at [subroutine divergence](https://github.com/xcompact3d/Incompact3d/blob/ae108f78f04765989c763a3cb67ab9d8cf4cde3f/navier.f90#L205). I can help with that is you need.

Best regards,
Felipe.

**Comment by shykafer** [comment]
Hey, 

thanks! Now it's clear where the misunderstanding and problem was. Anyway I will try to reconstruct the exact value by the snapshots, instead of writign the pp3 out of the subroutine. 

Best Kay
