### ISSUE TITLE
2-2-2 Dirichlet B.C. 

### ISSUE THREAD

**Issue by Xixiong-Guo** [xcompact3d/Incompact3d#31]
Hi all,

How to set up a Dirichlet boundary condition in Incompact3d?

For example, z_bottom all direction: u=0; other 5 boundary faces, u=1.

What I've done was that 1) set nclx1/n,ncly1/n,nclz1/n to 2 in BC-Cylinder.prm
2) comment boundary_conditions subroutine in incompact3d.f90  (I did all boundary velocity set up in pre_correc subroutine in navier.f90)
3) implement all velocity in pre_correc subroutine, such as 

  if (nclz1==2) then
     if (xstart(3)==1) then
        do j=1,xsize(2)
           do i=1,xsize(1)
              dpdxz1(i,j)=dpdxz1(i,j)*gdt(itr)
              dpdyz1(i,j)=dpdyz1(i,j)*gdt(itr)
           enddo
        enddo
        do j=1,xsize(2)
           do i=1,xsize(1)
              ux(i,j,1)=zero
              uy(i,j,1)=zero 
              uz(i,j,1)=zero 
           enddo
        enddo
     endif
  endif

  if (nclzn==2) then
     if (xend(3)==nz) then   
        do j=1,xsize(2)
           do i=1,xsize(1)
              dpdxzn(i,j)=dpdxzn(i,j)*gdt(itr)
              dpdyzn(i,j)=dpdyzn(i,j)*gdt(itr)
           enddo
        enddo
        do j=1,xsize(2)
           do i=1,xsize(1)
              ux(i,j,xsize(3))=one
              uy(i,j,xsize(3))=one
              uz(i,j,xsize(3))=one
           enddo
        enddo
     endif
  endif

Is this correct? Thanks a lot.

Xixiong

**Comment by ricardofrantz** [comment]
You don't have to change pre_correc. The same is designed to work and apply the pressure correction automatically (when needed) for all combinations of ncl. You may have to change it if you need to impose/compute a flow rate correction when using inflow/outflow. By default the following planes are forced to zero and imposed in the pre_correc with ncl..=2: bxx1,bxy1,bxz1,bxxn,bxyn,bxzn,byx1,byy1,byz1,byxn,byyn,byzn,bzx1,bzy1,bzz1,bzxn,bzyn,bzzn.

This means that by default the code imposes a no-slip condition when setting ncl..=2. If you want to impose a non-zero value, just specify the desired one (e.g. a fixed value or a 1-d outflow equation) in the correct plane in the bounday_conditions subroutine. 

Ricardo

**Comment by jxgxx** [comment]
Thanks Ricardo.
Just clarifying: you mean whatever B.C. (velocity based) applied, don't need to change pre_correc.
Only need to impose the velocity value in boundary_conditions subroutine?

Based on BC-Cylinder example, only two faces in x-direction are listed in boundary_conditions subroutine, then if I wish to impose a non-zero value to all other faces, I just need to imitate the inflow condition 

"  do k=1,xsize(3)
     do j=1,xsize(2)
        bxx1(j,k)=one+bxo(j,k)*noise1
        bxy1(j,k)=zero+byo(j,k)*noise1
        bxz1(j,k)=zero+bzo(j,k)*noise1
     enddo
  enddo"

to other faces?

**Comment by ricardofrantz** [comment]
Sorry for the delayed answer. If you set nclXX=2 it will force the desired boundary to no-slip because of bxx1,bxy1,bxz1,bxxn,bxyn,bxzn,byx1,byy1,byz1,byxn,byyn,byzn,bzx1,bzy1,bzz1,bzxn,bzyn,bzzn are all initialized as zero. It will only have a different value, e.g. a constant velocity or outflow velocity if specified at the subroutine boundary_conditions. If you wish to superimpose white noise at your inflow, it seems good to me the proposed way and you don't need to specify "zero" as it will be replacing last iteration value automatically:
 
```
do k=1,xsize(3)
do j=1,xsize(2)
bxx1(j,k)=one+bxo(j,k)*noise1
bxy1(j,k)=byo(j,k)*noise1
bxz1(j,k)=bzo(j,k)*noise1
enddo
enddo
```
Set the other faces the way I suggested and check in Paraview., you'll see they have zero velocity value. Ricardo
