### ISSUE TITLE
Working of variable "xnu" in ALM method

### ISSUE THREAD

**Issue by Prathamesh-Banda** [xcompact3d/Incompact3d#312]
Greetings, 
I am an MTech student and I am currently working on a code on ALM method in XCompact3D for a vertical axis wind turbine (VAWT). 

The code is modified for some endeffects model and some changes in dynamic stall.

I see that **xnu** variable is 1/re used as kinematic viscosity within the code. Generally in simulations, we dont really care about the fluid type (kinematic visc. or density) because Reynold's number is the main parameter.(correct me if I am wrong)

But for ALM method,we deliberately use air as the fluid (since we specify **rho_air** as 1.2 (for air) and use visc = xnu for few calculations ),  we are forced to input re = 66667 or values of same order (to make kinematic visc = 1.5e-5 as of real air).

So how do I simulate for re = 1e6
My turbine radius is 0.5m

**Comment by slaizet** [comment]
You can control the Reynolds with the incoming velocity.
Best,
Sylvain
