### ISSUE TITLE
velocity/velocity gradient in force.f90 

### ISSUE THREAD

**Issue by jxgxx** [xcompact3d/Incompact3d#32]
Hi all,

I want to add a few contents regarding velocity/velocity gradient for post-processing use. I choose to add in force.f90.

1. ux1,uy1,uz1 at the beginning of subroutine force.f90 should be the real velocity solution of each time step, right? I mean if I need velocity, then use ux1... in x pencil directly?

2. If I need to calculate du/dy, du/dz, I still need to transpose from x to y (calculate du/dy) to z (calculate du/dz), and then call dery, derz in relative pencil. Am I right?

Thanks.

**Comment by ricardofrantz** [comment]
Precisely, when you wish to calculate a derivative at a given direction (e.g. z-direction) the input data for the derivative call has to be in the same pencil of the derivative (e.g. 3). Regarding the second question, if you wish to accumulate the derivative results you can choose any pencil to do so, usually one will go with the pencil that minimizes the total number of operations.
