### ISSUE TITLE
On the drag calculation of cylinder?

### ISSUE THREAD

**Issue by yeechin** [xcompact3d/Incompact3d#33]
Dear all,

I am trying to write a code to evaluate the drag of an irregular surface based on the method used in the force.f90 of the cylinder case. However, it is bothering me that why on line 435 and 436, the term of pressure tpresx and tpresy are divided by dt? From my understanding, this two lines are not needed here. Could anyone please explain this to me? Best Regards.

**Comment by slaizet** [comment]
Lift and Drag are now ready to be used for the cylinder case in the new version of the code:
https://github.com/xcompact3d/Incompact3d
