### ISSUE TITLE
2decomp&fft

### ISSUE THREAD

**Issue by bkmgit** [xcompact3d/Incompact3d#34]
Do you expect to continue using 2decomp&fft ? If so, will this be fully integrated into the main code or be kept as a separate FFT library?

**Comment by ricardofrantz** [comment]
I don't think anyone has a better solution than 2decomp&fft for Incompact3d. It works and scales very well. We are discussing adding all 2decomp files in a single one, but is just a matter of organisation. What do you mean by "fully integrate into the main code"? Do you have a suggestion?

**Comment by bkmgit** [comment]
Some groups leave the FFT library as a separate entity to allow for updates, separate testing and incorporation in other codes. Do you expect to do further development of 2decomp&FFT?

**Comment by ricardofrantz** [comment]
As you can see in the Makefile, we currently have options to link the code with distributed FFT packages like Intel MKL, fftw3, etc or to use a generic package built in. This repository is not intended to distribute 2decomp&FFT specifically. As far as I am aware, there were no further developments in this library by the authors.
