### ISSUE TITLE
new paraview do not open xd

### ISSUE THREAD

**Issue by teruelfederico** [xcompact3d/Incompact3d#35]
I got this even though Paraview 5.0 open the same file well.

ERROR: In /build/paraview-NOjbRJ/paraview-5.1.2+dfsg1/ParaViewCore/ServerImplementation/Core/vtkSIProxy.cxx, line 310
vtkSISourceProxy (0x5590b29d8590): Failed to create vtkXdmfReader. Aborting for debugging purposes.

Does anyone knows how to solve this issue?
Thanks.

**Comment by ricardofrantz** [comment]
I’ve been using ParaView 5 smoothly. When you open the .xdmf file, be sure you Open Data With... XMDF Reader (1st option) instead of Xdmf3ReaderS/T. 
The error appears to be related with the XDMF reader itself, have you compiled ParaView by yourself?
Ricardo

**Comment by teruelfederico** [comment]
Thanks. I did not compile ParaView. I will try to go back to the 5.0 version.

**Comment by ricardofrantz** [comment]
I suggest downloading the latest, already compiled, version of ParaView from the official website. Just unzip and execute, very easy nowadays. I add a alias in the .bashrc to the bin folder executable. I remembered that the version distributed with Ubuntu “apt get” has some functionalities disabled and is badly outdated.
