### ISSUE TITLE
Is it possible to do DNS of open channel flow using Incompact3d?

### ISSUE THREAD

**Issue by YanchongDuan** [xcompact3d/Incompact3d#36]
As the Incompact3d can do DNS of channel flow (i.e., BC-Channel-flow.f90) whose boundary conditions are periodic in streawise and spanwise direction, and no slip in wall-normal direction with corresponding settings in the BC-Channel-flow.f90 file:
nclx1 = 0 !Boundary condition in x=0  (0: Periodic, 1:Free-slip, 2: Dirichlet) 
nclxn = 0 !Boundary condition in x=Lx (0: Periodic, 1:Free-slip, 2: Dirichlet) 
ncly1 = 2 !Boundary condition in y=0  (0: Periodic, 1:Free-slip, 2: Dirichlet) 
nclyn = 2 !Boundary condition in y=Ly (0: Periodic, 1:Free-slip, 2: Dirichlet) 
nclz1 = 0 !Boundary condition in z=0  (0: Periodic, 1:Free-slip, 2: Dirichlet) 
nclzn = 0 !Boundary condition in z=Lz (0: Periodic, 1:Free-slip, 2: Dirichlet) 

Comapred to channel flow, the only different boundary condition for open channel flow is nclyn which shoul be free-slip, i.e., nclyn=1. Now I wonder if this can be adopted in Incompact3d,or in other words, can we apply different boundary conditions at the start and end of the same direction(i.e., ncly1=2, nclyn=1)?

**Comment by fschuch** [comment]
Yes, it is possible. There is a little explanation at the Wiki page about [Extended boundary conditions](https://github.com/xcompact3d/Incompact3d/wiki/New-Features#extended-boundary-conditions).

Best regards,
Felipe.
