### ISSUE TITLE
Solicito ayuda con la instalación de incompact3d

### ISSUE THREAD

**Issue by cquevedo1** [xcompact3d/Incompact3d#39]
Hola, instalé Incompact3d y al tratar de ejecutarlo me aparece el siguiente mensaje: "mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well." Alguien podría brindarme un poco de ayuda.. Desde ya estoy agradecido

**Comment by ricardofrantz** [comment]
Hej, claramente el mpirun no está encontrando el archivo ejecutable. Asegúrese de haber finalizado la compilación y de estar usando la sintaxis de comando correcta. Mira la sección README si no estás seguro. suerte! 
Ricardo

**Comment by cquevedo1** [comment]
Si, entiendo el mensaje, pero he instalado por primera vez incompact3d y al ejecutar: mpirun -n 4 ./incompact3d, aparece ese error. Quizás estoy haciendo algún paso mal y por eso necesito soporte. Disculpen la molestia.
Saludos, Cristian.

**Comment by cquevedo1** [comment]
Yo he instalado la version de mpi 3.1 en lugar de la 1.1, es posible que ese sea el problema?

**Comment by cquevedo1** [comment]
He probado otros métodos y ahora me sale el siguiente error: Fatal Error: Can't open module file ‘mpi.mod’ for reading at (1): No existe el archivo o el directorio
compilation terminated.
