### ISSUE TITLE
Using IBM in lock-exchange

### ISSUE THREAD

**Issue by wtvrinc** [xcompact3d/Incompact3d#43]
Hi, 

Can someone possibly hint what I need to do to add IBM to the lock-exchange problem. I have modified the genepsi file, but I am stuck at linking it to the BC-lock-exchange file. 

Thanks.

**Comment by ricardofrantz** [comment]
Have you added the -DIBM flag in Makefile? Meld the .f90 from the cylinder and lock cases. It should be straightforward. Also keep in mind IBM cannot handle no-flux boundary condition at the moment, so I recommend using it with non-conservative currents.
Regards,
R.

**Comment by wtvrinc** [comment]
Thanks for the reply. I might have to think of a workaround. Density needs a no-flux B.C.

**Comment by wtvrinc** [comment]
Hi Ricardo, 

I am thinking is it possible for me to enforce a tanh profile for density across regions where epsilon is 1, to enforce no-flux across solid walls. That is, modify the scalar function that way. 

-Sunil

**Comment by fschuch** [comment]
Hi,

Please, take a look at this post at the [incompact3d user group](https://groups.google.com/forum/#!topic/incompact3d-user-group/MHIB80-ow7M).

**Comment by wtvrinc** [comment]
Thanks a lot. I will try to implement alternating ilag values. But if you could tell me, if I write a subroutine in derive.f90 and dependent fortran modules - where I will replace lagpol(xyz) with a tan hyperbolic function, will it cause problems in pencil decomposition/parallel strategy. 

Thank you,

**Comment by wtvrinc** [comment]
After imposing u=0 at epsilon=1 before scalar equation, that is. Anyway, 

Thanks
Sunil
