### ISSUE TITLE
Problems with outputs

### ISSUE THREAD

**Issue by brunopjacob** [xcompact3d/Incompact3d#47]
Hi all,

I am new to the code and I am a bit confused with the visualization tools implemented in the code. What is the input for the paraview_incompact3d.f90? Is it necessary to compile it separately? (right now, it seems that there are no dependency connection between the paraview_incompact3d.f90 and the xcompact3d.f90 files. Also, in the /Taylor_Green_Vortex dir, I don't understand the usage of post.prm. Is the post.prm file supposed to be an input to the program paraview_incompact3d?

Including a small description on how to post-process the data in the README would be very helpful :)

thanks,
Bruno

**Comment by slaizet** [comment]
Hi Bruno,

We are still working on the post-processing in xcompact3d. post.prm is an old input file but it is not in use anymore. I will make sure that all prm files are remove from the code. Regarding paraview_incompact3d.f90, you will need to compile it separately but you will have to configure it before to only read the 3D snapshots that you want. Hopefully things will get clearer in the future!

Cheers,

Sylvain
