### ISSUE TITLE
Mismatch between parameters.f90 and inputs.i3d

### ISSUE THREAD

**Issue by cpranav93** [xcompact3d/Incompact3d#50]
Hey,

This is Pranav. I was using the latest version of the code and I noticed a mismatch between the LESmodel inputs from inputs.i3d and in parameters.f90. Infact this causes a run-time error. We should probably fix it? 

The header for these parameters in inputs and in parameters are different (Turbulencemodel in inputs and LESmodel in parameters). Also there is a mismatch in the name of the LES model parameter (iles in inputs and jles in parameters).

Cheers,
Pranav

**Comment by fschuch** [comment]
Hi Pranav,

Can you send the `.i3d` file, so we can reproduce the error?
About the `parameters.f90`, I will take a look.

Best regards,
Felipe.

**Comment by cpranav93** [comment]
Hi Felipe,

Find attached the i3d file from example/Channel_Flow. It is the same for cylinder as well. 

A secondary point:
When I try to restart from a restart file, the simulation instantly goes to NaN beginning with the Div U*. I am not sure why this is. Do you have any suggestions on what could be the issue?

Best,
Pranav

**Comment by slaizet** [comment]
Hi Pranav,

OK I will fix the mismatch. The restart issue has been solved already.

Cheers,

Sylvain

**Comment by slaizet** [comment]
All done Pranav.
Cheers
