### ISSUE TITLE
How to impose B.C. on internal body and resolve the length and time scales?

### ISSUE THREAD

**Issue by nadeemmalik7** [xcompact3d/Incompact3d#51]
Hi all, I am new to this forum.

I want to start using Incompact3d for by particular system, which is similar to the channel with turbulence generating fractal (physical) grid reported in Laizet & Vassilicos FTC 87:673, 2011.

I have been the raw subroutines for generating the fractal grid ("square", "forcage_square") but still feeling my way around. How for example do I add this to the main code -- just add to the Makefile? Where do I call it? And suppose that I want to modify the x-location -- how?

Is the original code for LV2011 open source -- love to have if it is. Thanks.

After these minor details, I have two main questions.

(1) How to you impose the wall boundary conditions (i.e. <u,v,w>=<0,0,0>) at the surface of the physical grid? 
 
(2) I want to resolve the boundary layer and thus the shear layer close to the surface of the physical grid. Is this already implemented in the code/IBM method? If not how can this be done?

Any example codes of the above be welcome? 

Thanks
Nadeem Malik

**Comment by slaizet** [comment]
Hi Nadeem,

I sent you the original code for LV2011.

(1) not sure to understand the question, the IBM is imposing directly the no-slip BC at the wall of the immersed object (in your case, the physical grid)
(2) not sure to understand the question, if you impose a zero velocity at the wall of your immersed object, you will naturally create a boundary layer (which will be laminar) so there is no need to do anything

Best wishes

Sylvain

**Comment by nadeemmalik7** [comment]
Thanks Sylvain,

 

Things are sorted now, I have installed xcompact3d and it runs ok. 

 

Now just to sort out the paraview instructions, and mesh re-configuration for my new 3D Sparse Grid system.

 

Thanks,

Best wishes

 

Nadeem
