### ISSUE TITLE
Performance of the code compared to the previous version

### ISSUE THREAD

**Issue by jeromevetel** [xcompact3d/Incompact3d#52]
Hi all,

I currently test the new version of the code. Great job, thanks! However, by comparing the new version with the old one on a case of the backward-facing step flow, I remark that the simulation time is more than double. So I used the original files from both versions on the cylinder case, and same observation. I don't understand because for most users, a speedup between 10 and 20 % should be observed.

I suppose that more in-depth tests have been successfully performed on this and wonder why in my case this is not the case. Is there anybody experiencing the same observation?

thanks,
jerome

**Comment by fschuch** [comment]
Hi,

I will check it.

I just need a few pieces of information in order to reproduce the test:

- Your Operational System;
- Compiler version;
- Have you changed the compilation flags or are you using the standard for each case?

Best regards,
Felipe.

**Comment by jeromevetel** [comment]
Thanks for your reply Felipe.

I tested the code on:
- a few cores on macos, with gcc 9.3.0 and openmpi 4.0.3
- more cores on a compute serveur running CentOS 7, with gcc 7.3.0 and openmpi 3.1.1
- same server but with intelmpi 2018.3. However in this last case, compilation was not successful for the new version, but works with the old one. Note that I didn't try to solve this issue.

And I use the default compilation flags.

Thanks,
jerome

**Comment by slaizet** [comment]
Hi Jerome,

Are you sure there is no issues with double/single precision? or with the time advancement scheme? 

Cheers,

Sylvain

**Comment by jeromevetel** [comment]
Hi Sylvain,

Both versions use double precision, and AB3. Here are the output files on 4 cores on macOS, if this can help.

[output_new.txt](https://github.com/xcompact3d/Incompact3d/files/4546444/output_new.txt)
[output_old.txt](https://github.com/xcompact3d/Incompact3d/files/4546438/output_old.txt)

Sorry for that, don't want you to waste your time.

jerome

**Comment by slaizet** [comment]
OK I think I know what is the problem, you need to add -O3 option at the compilation. I will modify the Makefile soon.

Cheers

Sylvain

**Comment by jeromevetel** [comment]
WOW Sylvain,

I indeed missed that difference between the FFLAGS of the two code Makefiles! Now I understand why the compilation was previously so fast, to the detriment of the execution time, and now the new version is indeed faster than the new one!

MERCI BEAUCOUP !
jerome

**Comment by slaizet** [comment]
yeah, sorry about that, I need to change the Makefile!
