### ISSUE TITLE
Move case-specific intitlization / finalization to dedicated case subroutine

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/Incompact3d#53]
The file xcompact3d.f90 contains case-specific open / close statements. This should be moved inside the corresponding init and finalize subroutines in BC-xxx.f90.

https://github.com/xcompact3d/Incompact3d/blob/ca5be84f7aa4f92a355e4e4cb89becb493f238c3/src/xcompact3d.f90#L264

https://github.com/xcompact3d/Incompact3d/blob/ca5be84f7aa4f92a355e4e4cb89becb493f238c3/src/xcompact3d.f90#L292

However, the case/init subroutine is called only when irestart==0. It might be relevant to adapt the initial stage of xcompact3d. For instance :
- always call a subroutine case/boot
- then call the subroutine case/init when irestart==0

The case-specific open / close statements could then be moved inside case/boot and case/finalize

**Comment by mathrack** [comment]
See [this commit](https://github.com/mathrack/Incompact3d-1/commit/391643784377395f026cfa34b0fdb547ac9b88df), or [this one](https://github.com/mathrack/Incompact3d-1/commit/e69f1570d5fed9d73bfec50de3e5cd7de74d2f27) for instance

**Comment by fschuch** [comment]
That would be nice.

I also recommend making the parameters filename (`InputFN='input.i3d'`) global at [module_param.f90](./src/module_param.f90), so we can handle case-specific nameslists at case-specific files.
It would reduce a little bit the footprint of different modules and make it easier for us to drop in customized solutions.
