### ISSUE TITLE
Incorrect loop order

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/Incompact3d#57]
https://github.com/xcompact3d/Incompact3d/blob/e8f90c7fccd75b9c22899e2429754de5aa7c2b68/src/derive.f90#L5198

**Comment by mathrack** [comment]
https://github.com/xcompact3d/Incompact3d/blob/e8f90c7fccd75b9c22899e2429754de5aa7c2b68/src/derive.f90#L4994

**Comment by mathrack** [comment]
https://github.com/xcompact3d/Incompact3d/blob/e8f90c7fccd75b9c22899e2429754de5aa7c2b68/src/derive.f90#L4914

**Comment by mathrack** [comment]
https://github.com/xcompact3d/Incompact3d/blob/e8f90c7fccd75b9c22899e2429754de5aa7c2b68/src/derive.f90#L4902

**Comment by mathrack** [comment]
https://github.com/xcompact3d/Incompact3d/blob/e8f90c7fccd75b9c22899e2429754de5aa7c2b68/src/derive.f90#L4887

**Comment by mathrack** [comment]
https://github.com/xcompact3d/Incompact3d/blob/e8f90c7fccd75b9c22899e2429754de5aa7c2b68/src/derive.f90#L4871

**Comment by mathrack** [comment]
https://github.com/xcompact3d/Incompact3d/blob/e8f90c7fccd75b9c22899e2429754de5aa7c2b68/src/derive.f90#L4857

**Comment by slaizet** [comment]
Will deal with this as soon as the SFTC work is merged in the master branch. It should happen very soon!
Cheers,
Sylvain
