### ISSUE TITLE
Visualization error from paraview

### ISSUE THREAD

**Issue by jxgxx** [xcompact3d/Incompact3d#6]
Hi all,

I have problem when visualizing the output data. I put all ux,uy,uz files and snapshots xdmf into same directory, and open xdmf in paraview.  

The error as follows: ERROR: In C:\bbd\7cc78367\build\superbuild\paraview\src\VTK\IO\Xdmf2\vtkXdmfHeavyData.cxx, line 1214
vtkXdmfReader (0000027835AFD980): Failed to read attribute data

I ran cylinder case, and added -DIBM in Makefile, but didn't do anything on visu.f90, visu.prm, or any other relating to output. Should I?

Thanks.

**Comment by ricardofrantz** [comment]
The .xdmf's generated are designed to look for binary files in the ./data folder. 
I suggest avoiding moving files to the same folder if you wish the script to work.

PS: When opening the xdmf in Paraview, select **Xdmf Reader** instead of the Xdmf3 options.

Ricardo
