### ISSUE TITLE
Reduce derivatives order

### ISSUE THREAD

**Issue by leormonteiro** [xcompact3d/Incompact3d#7]
Hello again!

There is any way to reduce easily the order of spatial derivatives? I would like to make some test with 4th order.

Thank you!

**Comment by xcompact3duser** [comment]
You just need to change the coefficients in the subroutine scheme (you can follow Lele, S. K. (1992). Compact finite difference schemes with spectral-like resolution. Journal of computational physics, 103(1), 16-42.). Not too difficult but it is very easy to make a mistake so I suggest you to validate carefully the new coefficients.
