### ISSUE TITLE
Potential memory leak in FFT subroutines

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/Incompact3d#8]
Hi,

Deallocate statements are missing in the 3D FFT subroutines.

https://github.com/xcompact3d/Incompact3d/blob/687b5c17f58933548befc1a108c647a02a5d66e1/decomp2d/fft_common_3d.inc#L37

https://github.com/xcompact3d/Incompact3d/blob/687b5c17f58933548befc1a108c647a02a5d66e1/decomp2d/fft_common_3d.inc#L79

https://github.com/xcompact3d/Incompact3d/blob/687b5c17f58933548befc1a108c647a02a5d66e1/decomp2d/fft_common_3d.inc#L190

https://github.com/xcompact3d/Incompact3d/blob/687b5c17f58933548befc1a108c647a02a5d66e1/decomp2d/fft_common_3d.inc#L217

**Comment by mathrack** [comment]
A potential fix : https://github.com/mathrack/Incompact3d-1/commit/b796a12d2e0da6ae0e75fc95d0be14d4a0ebce53

**Comment by mathrack** [comment]
After investigation, the absence of "deallocate" statements should not leak memory because the array is not declared with the save attribute. https://community.intel.com/t5/Intel-Fortran-Compiler/Retention-of-allocated-memory-within-a-subroutine-that-is-called/td-p/1072829

**Comment by pbartholomew08** [comment]
It might still be worth doing deallocate:
1) It makes it explicit what is happening
2) Different compilers seem to treat SAVE (or lack of) differently from what I've read, so I wouldn't rely on it :)

**Comment by mathrack** [comment]
Makes sense. The fix I have proposed could be simplified : at the end of the subroutines, we could add

```
#ifndef OVERWRITE
if (allocated(wk1)) deallocate(wk1)
#endif
```

**Comment by pbartholomew08** [comment]
👍 looks good to me
