### ISSUE TITLE
Immersed boundry with stretched mesh

### ISSUE THREAD

**Issue by ArpitDs** [xcompact3d/Incompact3d#8]
Hello,

Is it possible to use immersed boundary method with the stretched mesh in the present version of code ?,  because theoretically i think its allowed , However when i try to use cylinder case with stretched mesh code is blowing up. 

i have added the -stretching flag in make file. Is that all that is needed or i am missing on something ?

regards,
Arpit

**Comment by ArpitDs** [comment]
I know that stretched mesh with IBM has been used in the periodic hill case, so my question w.r.t periodic BC in y direction. i.e ncly1=0 nclyn=0

**Comment by fschuch** [comment]
Dear Arpit,

Imersed boundary method (IBM) should work with stretching, like in the periodic hill case. 

It is on our known issue list that the forces module (-DFORCES compilation flag) is not computing properly with stretching, so I recommend removing the flag for now.

For the periodic case in y, are you using the correct number of points ny? At module_param.f90 file header, we have the possibilities for BC 1 (Free-slip) and 2 (Dirichlet), for 0 (Periodic) is necessary subtract one point.

Best regards,
Felipe.

**Comment by ArpitDs** [comment]
Dear Felipe,

Actually, i have been using Incompact for quite sometime now, so was aware of the fact that when you switch from free-slip, to periodic BC in y you have to reduce the number of grid point in y by 1. I have tried that but the solution is diverging . 

I have also tried removing the -DFORCES flag, but it does not seem to help. However stretching is working fine when i use it with Free-slip or Dirichlet BC.

Can you suggest something which might help me overcome this issue.

regards,
Arpit

**Comment by ArpitDs** [comment]
Ricardo, i am using istret =1 (center).

Arpit

**Comment by fschuch** [comment]
Can you please try the periodic with old-school IBM (ivirt=1 and ilag=0)?

**Comment by fschuch** [comment]
The code should work with periodic condition and refinement at center or both sides. Of course, refinement at the bottom is not compatible.

The solution for your case was presented [here](https://github.com/xcompact3d/Incompact3d/issues/13#issuecomment-387834636). The code ran properly in my test, please, let me know if you have any question.

**Comment by ArpitDs** [comment]
i tried with and also without the stretching flag  and ncly1 and nclyn=0, also i reduced no og grid point in ny by one, i have used beta =1.2 and 1.5, still the issue persist.

Am i doing something wrong something more needs to be done ?

**Comment by ArpitDs** [comment]
thank you its working, with the latest verison, i suppose some fix might have been committed,.

**Comment by ArpitDs** [comment]
sorry for inconvenience, it turns out i made mistake earlier could you please reply to my previous question ?
i am also attaching the files 
[BC-Cylinderf.txt](https://github.com/xcompact3d/Incompact3d/files/1993021/BC-Cylinderf.txt)
[BC-Cylinder.txt](https://github.com/xcompact3d/Incompact3d/files/1993022/BC-Cylinder.txt)

**Comment by fschuch** [comment]
Do you remove -DFORCES compilation flag? Notice that we made some changes on Makefile, it is now on line 32.

**Comment by ArpitDs** [comment]
yes i did remove the -DFORCES flag

**Comment by fschuch** [comment]
Sorry, I had a mistake about ran the code, it is not running in my tests with stretching and periodic condition in y. We probably have a bug somewhere, I'm working on it.
