### ISSUE TITLE
Memory usage at gene_epsi_3D

### ISSUE THREAD

**Issue by fschuch** [xcompact3d/Incompact3d#9]
The [`subroutine gene_epsi_3D`](https://github.com/xcompact3d/Incompact3d/blob/687b5c17f58933548befc1a108c647a02a5d66e1/src/genepsi3d.f90#L155)  was integrated into the main code as part of release 2.0. It came with two benefits, no more need for pre-processing, besides the performance and scalability with 2decomp. However, it demands large use of memory, mainly for the arrays `xepsi`, `yepsi` and `zepsi`.

In order to improve memory usage, I bring a few suggestions:

1. Just allocate them just if `iibm .eq. 2`, and preferable, do not have more than one allocated at the same time;
2. Since they are expected to be set just as zeros or ones, they could be changed to Boolean type (a huge reduction if compared to double or single float point).

Let me know what do you think about it, I could work on it.

It is also possible to produce the geometry externally with [xcompact3d-toolbox.genepsi ](https://xcompact3d-toolbox.readthedocs.io/en/latest/Docstrings.html#module-xcompact3d_toolbox.genepsi), but some bugs have to be solved ([#3](https://github.com/fschuch/xcompact3d_toolbox/issues/3))

**Comment by pbartholomew08** [comment]
I think disabling for non-IBM runs would certainly be a good starting point, the same could also be said for rho in non-LMN/free-surface (and I'm sure other arrays too)

**Comment by slaizet** [comment]
I would start with option 1 :-)
